### ISSUE TITLE
`eb --search` fails if `EASYBUILD_TRY_TOOLCHAIN` is set

### ISSUE THREAD

**Issue by riccardomurri** [hpcugent/easybuild-framework#1935] opened 2016-09-29 13:56 UTC
Invocation of `eb --search` fails if the environment variable `EASYBUILD_TRY_TOOLCHAIN` is set::

    $ export EASYBUILD_TRY_TOOLCHAIN=foss,2016b
    $ eb --search gawk
    == temporary log file in case of crash /tmp/eb-30naRL/easybuild-sqnQB9.log
    == Searching (case-insensitive) for 'gawk' in /tmp/eb-30naRL/tweaked_easyconfigs
    == Searching (case-insensitive) for 'gawk' in /opt/easybuild/ebfiles 
    == Searching (case-insensitive) for 'gawk' in /opt/easybuild/software/EasyBuild/2.9.0/lib/python2.7/site-packages/easybuild_easyconfigs-2.9.0-py2.7.egg/easybuild/easyconfigs 
     * /opt/easybuild/software/EasyBuild/2.9.0/lib/python2.7/site-packages/easybuild_easyconfigs-2.9.0-py2.7.egg/easybuild/easyconfigs/g/gawk/gawk-4.0.2-goolf-1.4.10.eb
     * /opt/easybuild/software/EasyBuild/2.9.0/lib/python2.7/site-packages/easybuild_easyconfigs-2.9.0-py2.7.egg/easybuild/easyconfigs/g/gawk/gawk-4.0.2-ictce-5.3.0.eb
    Traceback (most recent call last):
      File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
        "__main__", fname, loader, pkg_name)
      File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
        exec code in run_globals
      File "/opt/easybuild/software/EasyBuild/2.9.0/lib/python2.7/site-packages/easybuild_framework-2.9.0-py2.7.egg/easybuild/main.py", line 442, in <module>
        main()
      File "/opt/easybuild/software/EasyBuild/2.9.0/lib/python2.7/site-packages/easybuild_framework-2.9.0-py2.7.egg/easybuild/main.py", line 333, in main
        easyconfigs = tweak(easyconfigs, build_specs, modtool, targetdir=tweaked_ecs_path)
      File "/opt/easybuild/software/EasyBuild/2.9.0/lib/python2.7/site-packages/easybuild_framework-2.9.0-py2.7.egg/easybuild/framework/easyconfig/tweak.py", line 102, in tweak
        toolchain = orig_ecs[-1]['ec']['toolchain']
    IndexError: list index out of range

Unsetting the env. var. restores normal functionality::

    $ unset EASYBUILD_TRY_TOOLCHAIN
    $ eb --search gawk
    == temporary log file in case of crash /tmp/eb-7o9nBZ/easybuild-wrMJRE.log
    == Searching (case-insensitive) for 'gawk' in /opt/easybuild/ebfiles 
    == Searching (case-insensitive) for 'gawk' in /opt/easybuild/software/EasyBuild/2.9.0/lib/python2.7/site-packages/easybuild_easyconfigs-2.9.0-py2.7.egg/easybuild/easyconfigs 
     * /opt/easybuild/software/EasyBuild/2.9.0/lib/python2.7/site-packages/easybuild_easyconfigs-2.9.0-py2.7.egg/easybuild/easyconfigs/g/gawk/gawk-4.0.2-goolf-1.4.10.eb
     * /opt/easybuild/software/EasyBuild/2.9.0/lib/python2.7/site-packages/easybuild_easyconfigs-2.9.0-py2.7.egg/easybuild/easyconfigs/g/gawk/gawk-4.0.2-ictce-5.3.0.eb
    == No easyconfigs left to be built.
    == Temporary log file(s) /tmp/eb-7o9nBZ/easybuild-wrMJRE.log* have been removed.
    == Temporary directory /tmp/eb-7o9nBZ has been removed.

**Comment by riccardomurri** [comment] 2016-09-29 13:58
Actually, it looks like `eb --search` is somehow incompatible with `--try-toolchain`::

    $ eb --try-toolchain=foss,2016b --search gawk
    == temporary log file in case of crash /tmp/eb-hnB326/easybuild-ma5MUl.log
    == Searching (case-insensitive) for 'gawk' in /tmp/eb-hnB326/tweaked_easyconfigs
    == Searching (case-insensitive) for 'gawk' in /opt/easybuild/ebfiles
    == Searching (case-insensitive) for 'gawk' in /opt/easybuild/software/EasyBuild/2.9.0/lib/python2.7/site-packages/easybuild_easyconfigs-2.9.0-py2.7.egg/easybuild/easyconfigs
     * /opt/easybuild/software/EasyBuild/2.9.0/lib/python2.7/site-packages/easybuild_easyconfigs-2.9.0-py2.7.egg/easybuild/easyconfigs/g/gawk/gawk-4.0.2-goolf-1.4.10.eb
     * /opt/easybuild/software/EasyBuild/2.9.0/lib/python2.7/site-packages/easybuild_easyconfigs-2.9.0-py2.7.egg/easybuild/easyconfigs/g/gawk/gawk-4.0.2-ictce-5.3.0.eb
    Traceback (most recent call last):
      File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
        "__main__", fname, loader, pkg_name)
      File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
        exec code in run_globals
      File "/opt/easybuild/software/EasyBuild/2.9.0/lib/python2.7/site-packages/easybuild_framework-2.9.0-py2.7.egg/easybuild/main.py", line 442, in <module>
        main()
      File "/opt/easybuild/software/EasyBuild/2.9.0/lib/python2.7/site-packages/easybuild_framework-2.9.0-py2.7.egg/easybuild/main.py", line 333, in main
        easyconfigs = tweak(easyconfigs, build_specs, modtool, targetdir=tweaked_ecs_path)
      File "/opt/easybuild/software/EasyBuild/2.9.0/lib/python2.7/site-packages/easybuild_framework-2.9.0-py2.7.egg/easybuild/framework/easyconfig/tweak.py", line 102, in tweak
        toolchain = orig_ecs[-1]['ec']['toolchain']
    IndexError: list index out of range

**Comment by boegel** [comment] 2016-09-30 11:40
@riccardomurri duplicate of #1371, but thanks for bringing this up again, we should indeed get this fixes.

Whatever `--try-*` option is specified, it should be simply ignored when `--search` is used.

**Comment by boegel** [comment] 2016-09-30 12:18
fixed in #1937, thanks for reporting this (again) @riccardomurri!

**Closed by boegel** 2016-09-30 12:18 UTC
