### ISSUE TITLE
feature request - Don't prepend LD_LIBRARY_PATH

### ISSUE THREAD

**Issue by jerowe** [hpcugent/easybuild-framework#1791] opened 2016-06-02 07:42 UTC
Thanks for the great project!

I am using easybuild to deploy anaconda and conda env modules. Anaconda breaks everything when its lib is in the LD_LIBRARY_PATH. Reasons for this are explained more fully here:

http://superuser.com/questions/980250/environment-module-cannot-initialize-tcl

How can I tell the module-generator not to prepend LD_LIBRARY_PATH

?

**Comment by boegel** [comment] 2016-06-02 07:54
@jerowe Right now, you can't yet, at least not in a clean way, but we should indeed support this...
It's pretty much hardcoded in the framework now, see https://github.com/hpcugent/easybuild-framework/blob/master/easybuild/framework/easyblock.py#L1131 .

The only way would be to create a custom easyblock for Anaconda, and to override `make_module_req_guess`.

@cfenoy: you're familiar with this issue, would that suffice?

related: #1013

**Comment by ocaisa** [comment] 2016-06-02 08:12
You could also probably sidestep this by using Lmod instead of Tcl modules

**Comment by boegel** [comment] 2016-06-02 08:12
@ocaisa how exactly?

**Comment by ocaisa** [comment] 2016-06-02 08:15
From what I understood, the problem is with the `libtcl.so` that comes with anaconda, using Lmod (with lua modules?) you wouldn't need to open it

**Comment by boegel** [comment] 2016-06-02 08:17
I think it's way beyond just `libtcl.so`, also more common libraries.

And I think the problem is also that if you provide our own `libreadline.so` (& co) via `$LD_LIBRARY_PATH`, that Anaconda itself chokes on it...

So, it kind of works in both way, according to what I understood from @cfenoy.

**Comment by jerowe** [comment] 2016-06-02 10:01
I would prefer that the resolution not require Lmod.

I'm working on an anaconda block now, so I'll try overriding make_module_req_guess

Thanks!

**Comment by jerowe** [comment] 2016-06-02 12:11
It works! Thanks!

**Comment by boegel** [comment] 2016-06-02 12:14
@jerowe Please consider contributing back the easyblock/easyconfig, see also https://github.com/hpcugent/easybuild/wiki/Contributing-back .

If that's too much for now, please provide them via a gist (cfr. https://gist.github.com).

Also, please close this issue if you consider your problems answered.

**Comment by jerowe** [comment] 2016-06-02 12:39
I want to write a block for generating conda envs, but once I get those I will contribute them back. Thanks so much!

**Closed** 2016-06-03 14:49 UTC

**Comment by boegel** [comment] 2016-10-13 11:13
for what it's worth: support for avoiding that particular environment variables are updated in the modules generated by EasyBuild was added in #1943 via` --filter-env-vars=LD_LIBRARY_PATH`, and will be part of EasyBuild v3.0.0 .

The proper thing to do for Anaconda is to avoid that `$LD_LIBRARY_PATH` is set though, which should be done via the easyblock.
