### ISSUE TITLE
Intel MPI with Intel Fortran compiler must use mpiifort to be fully usable

### ISSUE THREAD

**Issue by akesandgren** [hpcugent/easybuild-framework#2000] opened 2016-11-16 18:25 UTC
The current setup of impi is that is sets the env vars:

```
I_MPI_F77=ifort
I_MPI_F90=ifort
I_MPI_FC=ifort
```

and uses `mpif90`

However, for complete Fortran90 support and the MPI fortran module (USE mpi in fortran code)
it really have to use mpiifort. A short example of why.

```
$ cat t-mpi_mod.f90 
PROGRAM main
USE mpi
INTEGER :: comm, amode, info, fh, ierror
CHARACTER(LEN=1) :: filename
CALL MPI_File_open( comm, filename, amode, info, fh, ierror)
END
```

```
mpif90 -c t-mpi_mod.f90 -v
mpif90 for the Intel(R) MPI Library 2017 Update 1 for Linux*
Copyright(C) 2003-2016, Intel Corporation.  All rights reserved.
ifort version 17.0.1
/pfs/software/eb/amd64_ubuntu1604_bdw/software/Core/ifort/2017.1.132-GCC-5.4.0-2.26/compilers_and_libraries_2017.1.132/linux/bin/intel64/fortcom
...
#include "..." search starts here:
#include <...> search starts here:
 .
 /hpc2n/eb/software/Compiler/intel/2017.1.132-GCC-5.4.0-2.26/impi/2017.1.132/intel64/include/gfortran/5.1.0
 /hpc2n/eb/software/Compiler/intel/2017.1.132-GCC-5.4.0-2.26/impi/2017.1.132/intel64/include
...
End of search list.
t-mpi_mod.f90(2): error #7013: This module file was not generated by any release of this compiler.   [MPI]
           USE mpi
```

```
While with mpiifort one gets:
mpiifort -c t-mpi_mod.f90 -v
mpiifort for the Intel(R) MPI Library 2017 Update 1 for Linux*
Copyright(C) 2003-2016, Intel Corporation.  All rights reserved.
ifort version 17.0.1
/pfs/software/eb/amd64_ubuntu1604_bdw/software/Core/ifort/2017.1.132-GCC-5.4.0-2.26/compilers_and_libraries_2017.1.132/linux/bin/intel64/fortcom
...
#include "..." search starts here:
#include <...> search starts here:
 .
 /hpc2n/eb/software/Compiler/intel/2017.1.132-GCC-5.4.0-2.26/impi/2017.1.132/intel64/include
...
 /usr/include
End of search list.
b-an01 [ake]$                       
```

and a successful compile.

edit by @boegel: formatting

**Comment by ocaisa** [comment] 2016-11-16 19:57
In your easyconfig for impi you need to set 
```
set_mpi_wrappers_all = True
```

**Comment by ocaisa** [comment] 2016-11-16 20:00
It's commented out in all the Intel MPI easyconfigs, we didn't set it by default because Intel don't do that either.

**Comment by akesandgren** [comment] 2016-11-16 20:14
I think it is a more fundamental problem, to be able to compile fortran90 code that uses code like

USE mpi

the command used MUST be mpiifort, thus it should ALWAYS be that way when using the intel compiler with intelmpi.

I.e. the code triggered by set_mpi_wrappers_all = true doesn't help, as the only thing it does it set the I_MPI_F* variables and add aliases for mpiifort.

I.e.,  MPI_COMPILER_MPIF90, etc, must be set to ifort for the combination of Intel compiler + IntelMPI, and only then. And for the intel+intelmpi combo the intel documentation clearly states that one should use mpiicc, mpiicpc, and mpiifort

Trying to come up with a working fix...

**Comment by ocaisa** [comment] 2016-11-16 21:08
I think I probably don't follow, are you talking about user space or internally within EB? EB does mpiifort internally already I'm pretty certain.

**Comment by akesandgren** [comment] 2016-11-16 21:14
I'm talking about what EB uses during an eb build. And it is not using mpiifort. At least not when building HDF5-1.8.7-intel-2016b.eb, nor is it using mpiicc.

**Comment by akesandgren** [comment] 2016-11-16 21:26
Ok, in toolchains/mpi there is the following class chain.
class IntelMPI(Mpich2):
  def _set_mpi_compiler_variables(self):
    super(IntelMPI, self)._set_mpi_compiler_variables()
      class Mpich2(Mpich):
        def _set_mpi_compiler_variables(self):
                   # hardwire MPI wrapper commands (otherwise Mpich parent class sets them based on MPICH version) 
                 self.MPI_COMPILER_MPIF77 = 'mpif77'
                 self.MPI_COMPILER_MPIF90 = 'mpif90'
                 self.MPI_COMPILER_MPIFC = 'mpif90'
                 super(Mpich2, self)._set_mpi_compiler_variables()

The end result being that MPIF77/F90/FC is set fo mpif77/f90/f90 always.

Now to fix this so that the intel compiler + intel mpi uses mpiifort and mpiicc, mpiicpc as it should, one can either add the same type of if-stmt from class Mpich to class Mpich2, or do a check for
if self.comp_family() == toolchain.INTELCOMP: in intelmpi.py after the call to super() and then change them to mpiifort, mpiicc etc.

Which way do you think is the best and most correct one considering the other code in there...

**Comment by akesandgren** [comment] 2016-11-16 21:49
Hmmm after checking some more i found out that it's probably not good enough to to the
if self.comp_family() == toolchain.INTELCOMP:
after the super() call in intelmpi. At least HDF5 needs to have FC set to mpiifort and not mpif90 (as it originally ends up as). So doing the check before the super() call and copying the if-stmt from mpich.py (if self.MPI_COMPILER_MPIF77 is None and...) to mpich2.py is the way to go.

**Comment by ocaisa** [comment] 2016-11-17 07:30
I tried to reproduce your error and I can't, mine compiles without problems once the environment variables are set:
```
setenv("I_MPI_CC","icc")
setenv("I_MPI_CXX","icpc")
setenv("I_MPI_F77","ifort")
setenv("I_MPI_F90","ifort")
setenv("I_MPI_FC","ifort")
```
I only have version 17.0.0 of the compiler available right now, is this error only a problem with 17.0.1?

**Comment by ocaisa** [comment] 2016-11-17 07:32
Actually it compiles even when the variables aren't set

**Comment by boegel** [comment] 2016-11-17 07:48
@akesandgren I would actually be very surprised as well if defining `$I_MPI_F90` to `ifort` and using `mpif90` isn't 100% equivalent with `mpiifort`... The latter is basically just an alias for the former, I *think*...

Also, we would have noticed already if that's not the case, why hasn't this popped up before?
We're missing something here...

When you're defining `$I_MPI_F90` in your tests, are you *exporting* it too?

I.e., does this work?

```
# should be equivalent with 'mpiifort example.f90'
export I_MPI_F90=ifort
mpif90 example.f90
```

**Comment by ocaisa** [comment] 2016-11-17 07:54
Are you using Intel with GCCcore 5.4.0 underneath? If your underlying GCC compiler is GCC4 then there might be problems with fortran modules since the format for fortran modules changed from GCC4 to GCC5 (see the fortran notes in https://gcc.gnu.org/gcc-5/changes.html)

**Comment by akesandgren** [comment] 2016-11-18 08:13
There is a very vital part of mpif90 that makes it useless for the ifort+intelmpi combo.

In mpif90 around line 607 in 2017.1, line 570 in impi 5.0.3.048, line 594 in impi 5.1.3.181, etc, one can see the following code snippet.

# Choose mod file corresponded gfortran version
gfort_ver=`$FC --version | head -n 1 | cut -d '(' -f1,2 | sed -e 's/\[.*//' | sed -e 's/.*(//' | sed -e 's/[a-zA-Z,/)]//g' | sed -e 's/^[[:space:]]*//' | sed -e 's/ .*//g' | sed -e 's/-.*//'`
if [ -n "$gfort_ver" ]; then
    #gfort_ver=`echo $gfort_ver | sed -e 's/gcc version //' | awk '{print $1}'`
    major=`echo $gfort_ver | awk -F. '{print $1}'`
    mid=`echo $gfort_ver | awk -F. '{print $2}'`
    low=`echo $gfort_ver | awk -F. '{print $3}'`
    case "$major" in
        4 ) 
...
        5 )
....
        * )
            gver="/5.1.0"
            ;;

modincdir="${modincdir}/gfortran${gver}"

Which results in mpif90 ALWAYS choosing a gfortran based fortran module variant and never an Intel ifort based one.

That is the main reason why the intel compiler + intel mpi combo MUST use the mpiicc/mpiicpc/mpiifort names and not use I_MPI_* or mpif90 --fc, mpicc -cc, etc. There is simply no way Fortran90 code using "USE mpi" can work otherwise.

**Comment by akesandgren** [comment] 2016-11-18 08:24
And no, mpiifort is not 100% equivalent top mpif90 and certainly not an alias for each other...

**Comment by ocaisa** [comment] 2016-11-18 08:39
But I tried your example and for me it worked fine so it certainly can work. Have you tried your example with other releases? Maybe this issue is specific to 17.0.1...and a bug?

**Comment by akesandgren** [comment] 2016-11-18 09:15
I, finally, did a diff of mpif90 between 2016.3 and 2017.1, and there is indeed a change in 2017 that is causing this.

====
        * )
-           gver=""
+           gver="/5.1.0"
            ;;
     esac
 else
-    gver=""
+    gver="/5.1.0"
====

So yes, the 2017 version of mpif90 always uses a GNU dir for the fortran .mod files.
Might be called a bug if you like. Still it is much better to make sure the toolchain uses mpiifort/mpiicc/mpiicpc to protect against problems like this in the future...

**Comment by ocaisa** [comment] 2016-11-18 09:26
Looks like this was introduced specifically in 2017.1.132 because it doesn't exist in 2017.0.098...anyone feel like reporting it to Intel?

**Comment by ocaisa** [comment] 2016-11-18 09:34
Can someone else verify that? I don't have 2017.1 installed to check

**Comment by akesandgren** [comment] 2016-11-18 09:45
Well, the change is not a bug as such. It's a catch-all for gfortran 6 (lazy coding yes...) but that's probably what they are going to answer with :-)

What should be considered a bug, though, is that the "else" part of that if-stmt also sets gver="/5.1.0", i.e., when it doesn't get any output at all from the --version cmd...

Regardless, using mpiifort et.al is still the most correct way of doing this since that follows the Intel recommendations.

**Comment by ocaisa** [comment] 2016-11-18 11:55
But this also means that `mpif90 -f90=ifort` does not work? Surely that's a bug, not supporting their own compiler with this script doesn't seem like a very smart move.

I would bite and open an issue to see what they say but I don't have that version available to double-check the error.

**Comment by akesandgren** [comment] 2016-11-18 12:02
Well, i'll guess that they will respond something like: mpif90 is not to support intel fortran, use mpiifort for that..... :-)

**Comment by boegel** [comment] 2016-11-18 22:09
@akesandgren We can certainly switch to `mpiifort` & co, I don't have any strong arguments against that, certainly not if `mpif90` + defining `$I_MPI_F90` isn't (always) working correctly.

But this is 100% sure a bug/regression in Intel MPI 2017.01 imho, so we should definitely report it.
It has always worked with earlier versions, or we would have noticed this.

To format code blocks, just use triple quotes before/after, see https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by fgeorgatos** [comment] 2016-11-23 09:25
tagging @besserox for further comment, in case there is one.

**Comment by boegel** [comment] 2016-11-26 14:50
fixed in #2005 by switching to `mpiifort` & co, thanks for reporting this @akesandgren and working out a fix!

**Closed by boegel** 2016-11-26 14:50 UTC

**Comment by damianam** [comment] 2017-06-27 12:10
> But this is 100% sure a bug/regression in Intel MPI 2017.01 imho, so we should definitely report it.
It has always worked with earlier versions, or we would have noticed this.

@boegel I agree. But have somebody already done it? If not, we'll do it this week.

**Comment by boegel** [comment] 2017-06-27 12:17
@damianam I didn't report it, I don't know of someone else doing it.

**Comment by ocaisa** [comment] 2017-06-27 12:21
@damianam Looking back over the thread I don't think anyone actually reported it

**Comment by damianam** [comment] 2017-06-27 12:26
Ok, we'll get to it then.
