### ISSUE TITLE
Issues during configuration of GCCcore on Ubuntu 16.04

### ISSUE THREAD

**Issue by SethosII** [hpcugent/easybuild-framework#2019] opened 2016-11-23 11:39 UTC
I'm trying to build several modules with EasyBuild on Ubuntu 16.04 but they all fail during configuration of GCCcore. On a Ubuntu 14.04 they all work as expected. For example Bowtie2-2.2.9-foss-2016a.eb without anything preexisting:

```
eb --buildpath=/dev/shm --module-syntax=Lua --modules-tool=Lmod --optarch=march=corei7 --prefix=/mnt/fhgfs_ribdata/user_worktmp/itadmin/easybuild/ Bowtie2-2.2.9-foss-2016a.eb -D
== temporary log file in case of crash /tmp/eb-0aiO82/easybuild-dWj5ZF.log
Dry run: printing build status of easyconfigs and dependencies
CFGS=/mnt/fhgfs_ribdata/user_worktmp/itadmin/easybuild/software/EasyBuild/2.9.0/lib/python2.7/site-packages/easybuild_easyconfigs-2.9.0-py2.7.egg/easybuild/easyconfigs
 * [ ] $CFGS/m/M4/M4-1.4.17.eb (module: M4/1.4.17)
 * [ ] $CFGS/a/Autoconf/Autoconf-2.69.eb (module: Autoconf/2.69)
 * [ ] $CFGS/a/Automake/Automake-1.15.eb (module: Automake/1.15)
 * [ ] $CFGS/l/libtool/libtool-2.4.6.eb (module: libtool/2.4.6)
 * [ ] $CFGS/f/flex/flex-2.5.39.eb (module: flex/2.5.39)
 * [ ] $CFGS/a/Autotools/Autotools-20150215.eb (module: Autotools/20150215)
 * [ ] $CFGS/b/Bison/Bison-3.0.4.eb (module: Bison/3.0.4)
 * [ ] $CFGS/z/zlib/zlib-1.2.8.eb (module: zlib/1.2.8)
 * [ ] $CFGS/b/binutils/binutils-2.25.eb (module: binutils/2.25)
 * [ ] $CFGS/g/GCCcore/GCCcore-4.9.3.eb (module: GCCcore/4.9.3)
 * [ ] $CFGS/m/M4/M4-1.4.17-GCCcore-4.9.3.eb (module: M4/1.4.17-GCCcore-4.9.3)
 * [ ] $CFGS/f/flex/flex-2.5.39-GCCcore-4.9.3.eb (module: flex/2.5.39-GCCcore-4.9.3)
 * [ ] $CFGS/b/Bison/Bison-3.0.4-GCCcore-4.9.3.eb (module: Bison/3.0.4-GCCcore-4.9.3)
 * [ ] $CFGS/z/zlib/zlib-1.2.8-GCCcore-4.9.3.eb (module: zlib/1.2.8-GCCcore-4.9.3)
 * [ ] $CFGS/b/binutils/binutils-2.25-GCCcore-4.9.3.eb (module: binutils/2.25-GCCcore-4.9.3)
 * [ ] $CFGS/g/GCC/GCC-4.9.3-2.25.eb (module: GCC/4.9.3-2.25)
 * [ ] $CFGS/o/OpenBLAS/OpenBLAS-0.2.15-GCC-4.9.3-2.25-LAPACK-3.6.0.eb (module: OpenBLAS/0.2.15-GCC-4.9.3-2.25-LAPACK-3.6.0)
 * [ ] $CFGS/n/numactl/numactl-2.0.11-GCC-4.9.3-2.25.eb (module: numactl/2.0.11-GCC-4.9.3-2.25)
 * [ ] $CFGS/h/hwloc/hwloc-1.11.2-GCC-4.9.3-2.25.eb (module: hwloc/1.11.2-GCC-4.9.3-2.25)
 * [ ] $CFGS/o/OpenMPI/OpenMPI-1.10.2-GCC-4.9.3-2.25.eb (module: OpenMPI/1.10.2-GCC-4.9.3-2.25)
 * [ ] $CFGS/g/gompi/gompi-2016a.eb (module: gompi/2016a)
 * [ ] $CFGS/f/FFTW/FFTW-3.3.4-gompi-2016a.eb (module: FFTW/3.3.4-gompi-2016a)
 * [ ] $CFGS/s/ScaLAPACK/ScaLAPACK-2.0.2-gompi-2016a-OpenBLAS-0.2.15-LAPACK-3.6.0.eb (module: ScaLAPACK/2.0.2-gompi-2016a-OpenBLAS-0.2.15-LAPACK-3.6.0)
 * [ ] $CFGS/f/foss/foss-2016a.eb (module: foss/2016a)
 * [ ] $CFGS/b/Bowtie2/Bowtie2-2.2.9-foss-2016a.eb (module: Bowtie2/2.2.9-foss-2016a)
== Temporary log file(s) /tmp/eb-0aiO82/easybuild-dWj5ZF.log* have been removed.
== Temporary directory /tmp/eb-0aiO82 has been removed.
```

Which runs fine until the configuraton of GCCcore:

```
eb --buildpath=/dev/shm --module-syntax=Lua --modules-tool=Lmod --optarch=march=corei7 --prefix=/mnt/fhgfs_ribdata/user_worktmp/itadmin/easybuild/ Bowtie2-2.2.9-foss-2016a.eb -dr
== temporary log file in case of crash /tmp/eb-HeOxMY/easybuild-tS0oQF.log
== resolving dependencies ...

...

== processing EasyBuild easyconfig /mnt/fhgfs_ribdata/user_worktmp/itadmin/easybuild/software/EasyBuild/2.9.0/lib/python2.7/site-packages/easybuild_easyconfigs-2.9.0-py2.7.egg/easybuild/easyconfigs/g/GCCcore/GCCcore-4.9.3.eb
== building and installing GCCcore/4.9.3...
== fetching files...
== creating build dir, resetting environment...
== unpacking...
== patching...
== preparing...
== configuring...
== FAILED: Installation ended unsuccessfully (build directory: /dev/shm/GCCcore/4.9.3/dummy-): build failed (first 300 chars): cmd " ../configure   --enable-languages=c,c++,fortran --enable-lto --enable-checking=release  --disable-multilib --enable-shared=yes --enable-static=yes  --enable-threads=posix  --enable-gold=default --enable-plugins  --enable-ld --with-plugin-ld=ld.gold  --enable-bootstrap --prefix=/mnt/fhgfs_ribda
== Results of the build can be found in the log file(s) /tmp/eb-HeOxMY/easybuild-GCCcore-4.9.3-20161123.115627.fbPnn.log
ERROR: Build of /mnt/fhgfs_ribdata/user_worktmp/itadmin/easybuild/software/EasyBuild/2.9.0/lib/python2.7/site-packages/easybuild_easyconfigs-2.9.0-py2.7.egg/easybuild/easyconfigs/g/GCCcore/GCCcore-4.9.3.eb failed (err: 'build failed (first 300 chars): cmd " ../configure   --enable-languages=c,c++,fortran --enable-lto --enable-checking=release  --disable-multilib --enable-shared=yes --enable-static=yes  --enable-threads=posix  --enable-gold=default --enable-plugins  --enable-ld --with-plugin-ld=ld.gold  --enable-bootstrap --prefix=/mnt/fhgfs_ribda')
```

The relevant lines are in the EasyBuild log of GCCcore are:

```
configure: error: in `/dev/shm/GCCcore/4.9.3/dummy-/gcc-4.9.3/obj':
configure: error: C compiler cannot create executables
See `config.log' for more details.
 (at easybuild/software/EasyBuild/2.9.0/lib/python2.7/site-packages/easybuild_framework-2.9.0-py2.7.egg/easybuild/tools/run.py:438 in parse_cmd_output)
```

And the config.log which indicates that the ld from EasyBuilds binutils:

```
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 
configure:4249: $? = 0
configure:4238: gcc -V >&5
gcc: error: unrecognized command line option '-V'
gcc: fatal error: no input files
compilation terminated.
configure:4249: $? = 1
configure:4238: gcc -qversion >&5
gcc: error: unrecognized command line option '-qversion'
gcc: fatal error: no input files
compilation terminated.
configure:4249: $? = 1
configure:4269: checking for C compiler default output file name
configure:4291: gcc    conftest.c  >&5
/mnt/fhgfs_ribdata/user_worktmp/itadmin/easybuild/software/binutils/2.25/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/crti.o: unrecognized relocation (0x2a) in section `.init'
/mnt/fhgfs_ribdata/user_worktmp/itadmin/easybuild/software/binutils/2.25/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
configure:4295: $? = 1
configure:4332: result: 
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME ""
| #define PACKAGE_TARNAME ""
| #define PACKAGE_VERSION ""
| #define PACKAGE_STRING ""
| #define PACKAGE_BUGREPORT ""
| #define PACKAGE_URL ""
| /* end confdefs.h.  */
| 
| int
| main ()
| {
| 
|   ;
|   return 0;
| }
configure:4338: error: in `/dev/shm/GCCcore/4.9.3/dummy-/gcc-4.9.3/obj':
configure:4342: error: C compiler cannot create executables
See `config.log' for more details.
```

Here are the complete log files: [config.txt](https://github.com/hpcugent/easybuild-framework/files/608684/config.txt), [easybuild-GCCcore-4.9.3-20161123.115627.fbPnn.txt](https://github.com/hpcugent/easybuild-framework/files/608685/easybuild-GCCcore-4.9.3-20161123.115627.fbPnn.txt).

Using the binutils from EasyBuild a simple "hello world" program also fails to compile with, so the issue seems to be there:

```
gcc -o hello_world hello_world.c 
/mnt/fhgfs_ribdata/user_worktmp/itadmin/easybuild/software/binutils/2.25/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/crti.o: unrecognized relocation (0x2a) in section `.init'
/mnt/fhgfs_ribdata/user_worktmp/itadmin/easybuild/software/binutils/2.25/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
```

As already said EasyBuild runs fine on Ubuntu 14.04. Am I missing something or what could be different between Ubuntu 14.04 and 16.04?

Using: Ubuntu server 16.04.1, EasyBuild 2.9.0, Lmod 5.7.2.

**Comment by ocaisa** [comment] 2016-11-23 12:03
Ubuntu 16.04 uses binutils 2.26.1 on the system and going backwards to `2.26` is what is causing the error I think. You need to change the definition of GCCcore so that it uses `2.26.1` instead...or take the lazy way out and do:
```
eb --buildpath=/dev/shm --module-syntax=Lua --modules-tool=Lmod --optarch=march=corei7 --prefix=/mnt/fhgfs_ribdata/user_worktmp/itadmin/easybuild/  --try-toolchain-version=2016b Bowtie2-2.2.9-foss-2016a.eb
```
which tells it to (try to) swap out `foss/2016a` for `foss/2016b`

**Comment by SethosII** [comment] 2016-11-23 14:21
Hey @ocaisa, using toolchain foss-2016b worked, thanks. But I don't understand why this is needed. Isn't EasyBuild building it's own version of binutils (which succeeds) which should then be independent of the systems version or do I misunderstand something?

**Comment by boegel** [comment] 2016-11-23 15:11
@SethosII The problem is not so much with the binutils being used by EasyBuild, but some files that are (still) grabbed from the OS (i.e. `crti.o` in this case), which were built with a newer version of binutils than the one being used by EasyBuild.

Although we try to avoid picking up stuff from the OS, it's not airtight yet, e.g. we still pick up `glibc`.

**Comment by SethosII** [comment] 2016-11-23 15:18
Ok, thank you for the clarification @boegel!

**Comment by boegel** [comment] 2016-11-23 15:38
@SethosII unless you have any more questions, please close this issue

**Closed** 2016-11-23 16:06 UTC
