### ISSUE TITLE
problem building Python-2.7.5-ictce-6.2.5.eb and mpi4py extension  with --rpath

### ISSUE THREAD

**Issue by pescobar** [hpcugent/easybuild-framework#2055] opened 2016-12-10 21:17 UTC
The crash appears when building the `mpi4py` extension.

The interesting messages start in line 56084

```
56084 icc: command line warning #10006: ignoring unknown option '-rpath'
56085 ipo: warning #11016: Warning unknown option -Xlinker
56086 /usr/bin/ld: cannot find -linker
56087 failure.
56088 removing: _configtest.c _configtest.o
56089 error: Cannot link MPI programs. Check your configuration!!!
```

Here is the full debug log:
https://gist.github.com/d5190e29433eab8e8544b8d6c98e1497

**Comment by jdonners** [comment] 2017-02-24 10:15
Hi,

this is most probably caused by the rpath_args.py script, which removes the flag --enable-new-dtags from the command line. The compiler passes this flag to the linker using '-Wl, --enable-new-dtags' or '-Xlinker --enable-new-dtags'. The script would then remove --enable-new-dtags and the compiler basically passes whatever random flag is next on the command-line on to the linker. I created a simple fix to the problem, which replaces --enable-new-dtags with --disable-new-dtags:

https://github.com/sara-nl/easybuild-framework/commit/3ec052c05b3b7e47c3922aaab023a02d4a1bab8d

I'll try to add a pull request to this issue..

**Comment by jdonners** [comment] 2017-02-24 10:23
hmm, I'm not authorized to do that. Should I have created a separate branch from develop?

**Comment by boegel** [comment] 2017-02-24 13:21
@jdonners Does the documentation at http://easybuild.readthedocs.io/en/latest/Contributing.html#pull-requests help?

**Comment by jdonners** [comment] 2017-02-24 14:38
pull request is here: https://github.com/hpcugent/easybuild-framework/pull/2131

**Comment by boegel** [comment] 2017-02-28 15:04
@pescobar @jdonners's PR #2131 with the fix for this issue is merged into `develop`, please check whether this solves the problem you were seeing?

**Comment by jdonners** [comment] 2017-06-12 20:47
I didn't check the exact version that @pescobar used, but I could build Python-2.7.12-intel-2016b.eb including mpi4py using --rpath

**Comment by boegel** [comment] 2017-06-13 07:46
OK, I'll close this as fixed, thanks for the fix & feedback @jdonners!

**Closed by boegel** 2017-06-13 07:46 UTC
