### ISSUE TITLE
problem migrating easyconfigs to 2.0.0

### ISSUE THREAD

**Issue by pescobar** [hpcugent/easybuild-framework#1236] opened 2015-03-21 12:31 UTC
Hi

I had this easyconfig working fine with EB-1.16.1 
https://gist.github.com/31d790ab9609ab01b26e

After adapting it to EB 2.x using the provided script  this is what I have now (changed premake to prebuild)
https://gist.github.com/b5cb381f723210ce89e8

But now it fails building. Here is the debug log
https://gist.github.com/b369d9d9463b98128013

It looks easybuild it's not executing "make  opt && make openmp".

I have a similar issue when trying this easyconfig with EB-2.0.0 when changing premakeopts to prebuildopts
https://gist.github.com/0432427864fa17421f65

Any clue about how to fix it?
thanks

**Comment by boegel** [comment] 2015-03-21 12:40
I don't see how this easyconfig could have worked with EB v1.16.1...

When you're specifying a list for `(pre)buildopts`, you're telling EB to run the configure-build-install cycle multiple times.

But, when using `MakeCp`, this typically doesn't work out well, since the install step requires certain binaries to be there.

EB never gets to running `make opt && make openmp`, because copying `minimac/bin/minimac` fails after the first cycle in which `cd libStatGen && make` is being run in the build step...

**Comment by pescobar** [comment] 2015-03-21 12:42
this is the buildlog of this easyconfig working with EB-1.x
https://gist.github.com/anonymous/e31859c6ec834dc68a9a

**Comment by boegel** [comment] 2015-03-21 13:34
I can't reproduce this working with EB v1.x, and it shouldn't have worked either, as far as I can tell...

**Comment by boegel** [comment] 2015-03-21 14:10
fixed in https://github.com/hpcugent/easybuild-easyconfigs/pull/815

**Closed by boegel** 2015-03-21 14:10 UTC
