### ISSUE TITLE
Group write permissions for shared easybuild installation

### ISSUE THREAD

**Issue by gppezzi** [hpcugent/easybuild-framework#1303] opened 2015-06-25 16:53 UTC
We'd like to share the easybuild installation directory with write permissions at group level: everyone from the group should be able to install, remove  and update existing apps & modules.

I managed to configure that (thanks to Alan's @ JSC example), by using --set-umask=002 & --set-gid-bit, however at some point EB decides to remove the group permissions:

https://github.com/hpcugent/easybuild-framework/blob/master/easybuild/framework/easyblock.py#L1533

As a workaround I commented that line out on my EB and it seems to work as I expect, so I'm opening an issue to see if we can find a better solution (not sure if the problem comes from my permissions).

**Comment by ocaisa** [comment] 2015-06-25 21:15
This is actually working as designed, the philosophy is that anyone can install a new version but only the responsible person (owner) for an installation can overwrite something that already exists.

On 25 Jun 2015 6:53 pm, "gppezzi" <notifications@github.com<mailto:notifications@github.com>> wrote:

We'd like to share the easybuild installation directory with write permissions at group level: everyone from the group should be able to install, remove and update existing apps & modules.

I managed to configure that (thanks to Alan's @ JSC example), by using --set-umask=002 & --set-gid-bit, however at some point EB decides to remove the group permissions:

https://github.com/hpcugent/easybuild-framework/blob/master/easybuild/framework/easyblock.py#L1533

As a workaround I commented that line out on my EB and it seems to work as I expect, so I'm opening an issue to see if we can find a better solution (not sure if the problem comes from my permissions).

—
Reply to this email directly or view it on GitHub<https://github.com/hpcugent/easybuild-framework/issues/1303>.


------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------
Forschungszentrum Juelich GmbH
52425 Juelich
Sitz der Gesellschaft: Juelich
Eingetragen im Handelsregister des Amtsgerichts Dueren Nr. HR B 3498
Vorsitzender des Aufsichtsrats: MinDir Dr. Karl Eugen Huthmacher
Geschaeftsfuehrung: Prof. Dr.-Ing. Wolfgang Marquardt (Vorsitzender),
Karsten Beneke (stellv. Vorsitzender), Prof. Dr.-Ing. Harald Bolt,
Prof. Dr. Sebastian M. Schmidt
------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------

**Comment by boegel** [comment] 2015-06-26 07:40
Well, I guess the issue is that it's hardcoded now, and there's no switch for disabling this in case you wanted to.

Adding such a switch is not difficult, and having it there makes sense to me.

**Comment by gppezzi** [comment] 2015-06-26 07:55
People from our group do not have root permissions, so i'm wondering if removing g-w permission by default will be a pain (for example when we need to re-install a package and the owner is away). We can always install a new version using another suffix, but we are in the very early days of easybuild here and I'd like to avoid such problems for new EB users. 

We might fallback to the default behaviour once user have more expertise on EB, but as @boegel said it would be nice have a switch on that.

**Comment by boegel** [comment] 2015-06-26 08:26
pull request in https://github.com/hpcugent/easybuild-framework/pull/1304, please review

**Comment by boegel** [comment] 2015-07-12 17:21
#1304 is merged, adds configuration options `--read-only-installdir` and `--group-writable-installdir` (will be included in EB v2.2.0)

**Closed by boegel** 2015-07-12 17:21 UTC
