### ISSUE TITLE
Problem running bootstrap.py: name 'sys_platform' is not defined.

### ISSUE THREAD

**Issue by Louwrensth** [hpcugent/easybuild-framework#1099] opened 2014-11-27 13:45 UTC
I want to install easybuild via the bootstrap.py script. But it is failing on me. What am I doing wrong?

I got modules and python ready:
```
$ module --version
VERSION=3.2.10
[...]
$ python -V
Python 2.7.8

$ curl -O -L https://raw.githubusercontent.com/hpcugent/easybuild-framework/master/easybuild/scripts/bootstrap_eb.py  
```

I edited bootstrap_eb.py to turn on debug printing.

This is the result.
```
$ python bootstrap_eb.py ~/.local/easybuild
[[DEBUG]] Going to use /tmp/tmplt02Gt as temporary directory
[[DEBUG]] Output from modulecmd python help:
  Modules Release 3.2.10 2012-12-21 (Copyright GNU GPL v2 1991):

  Usage: module [ switches ] [ subcommand ] [subcommand-args ]

Switches:
        -H|--help               this usage info
        -V|--version            modules version & configuration options
        -f|--force              force active dependency resolution
        -t|--terse              terse    format avail and list format
        -l|--long               long     format avail and list format
        -h|--human              readable format avail and list format
        -v|--verbose            enable  verbose messages
        -s|--silent             disable verbose messages
        -c|--create             create caches for avail and apropos
        -i|--icase              case insensitive
        -u|--userlvl <lvl>      set user level to (nov[ice],exp[ert],adv[anced])
  Available SubCommands and Args:
        + add|load              modulefile [modulefile ...]
        + rm|unload             modulefile [modulefile ...]
        + switch|swap           [modulefile1] modulefile2
        + display|show          modulefile [modulefile ...]
        + avail                 [modulefile [modulefile ...]]
        + use [-a|--append]     dir [dir ...]
        + unuse                 dir [dir ...]
        + update
        + refresh
        + purge
        + list
        + clear
        + help                  [modulefile [modulefile ...]]
        + whatis                [modulefile [modulefile ...]]
        + apropos|keyword       string
        + initadd               modulefile [modulefile ...]
        + initprepend           modulefile [modulefile ...]
        + initrm                modulefile [modulefile ...]
        + initswitch            modulefile1 modulefile2
        + initlist
        + initclear


[[INFO]] Found module command 'modulecmd' (EnvironmentModulesC), so using it.
[[DEBUG]] Excluding /home/ITER/vandell/Soft/Installers/easybuild-master from sys.path
[[DEBUG]] sys.path after cleaning: ['/work/imas/opt/python/2.7.8/lib/python27.zip', '/work/imas/opt/python/2.7.8/lib/python2.7', '/work/imas/opt/python/2.7.8/lib/python2.7/plat-linux2', '/work/imas/opt/python/2.7.8/lib/python2.7/lib-tk', '/work/imas/opt/python/2.7.8/lib/python2.7/lib-old', '/work/imas/opt/python/2.7.8/lib/python2.7/lib-dynload', '/work/imas/opt/python/2.7.8/lib/python2.7/site-packages']
[[INFO]]

+++ STAGE 0: installing distribute via included (patched) distribute_setup.py...


[[DEBUG]] preparing environment...
[[DEBUG]] Preparing for path /tmp/tmplt02Gt
[[DEBUG]] os.environ['PYTHONPATH'] after reset:
[[DEBUG]] $EASYBUILD_MODULES_TOOL set to EnvironmentModulesC
[[DEBUG]] distribute_setup.__file__: /tmp/tmplt02Gt/distribute_setup.py
Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.34.tar.gz
Extracting in /tmp/tmplP35TH
Now working in /tmp/tmplP35TH/distribute-0.6.34
Installing Distribute
Before install bootstrap.
Scanning installed packages
Setuptools installation detected at /work/imas/opt/python/2.7.8/lib/python2.7/site-packages
Not patching, --root or --prefix is installing Distribute in another location
Traceback (most recent call last):
  File "setup.py", line 248, in <module>
    scripts = scripts,
  File "/work/imas/opt/python/2.7.8/lib/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "/tmp/tmplP35TH/distribute-0.6.34/setuptools/dist.py", line 225, in __init__
    _Distribution.__init__(self,attrs)
  File "/work/imas/opt/python/2.7.8/lib/python2.7/distutils/dist.py", line 287, in __init__
    self.finalize_options()
  File "/tmp/tmplP35TH/distribute-0.6.34/setuptools/dist.py", line 257, in finalize_options
    ep.require(installer=self.fetch_build_egg)
  File "/tmp/tmplP35TH/distribute-0.6.34/pkg_resources.py", line 2025, in require
    working_set.resolve(self.dist.requires(self.extras),env,installer))
  File "/tmp/tmplP35TH/distribute-0.6.34/pkg_resources.py", line 2235, in requires
    dm = self._dep_map
  File "/tmp/tmplP35TH/distribute-0.6.34/pkg_resources.py", line 2464, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/tmp/tmplP35TH/distribute-0.6.34/pkg_resources.py", line 2497, in _compute_dependencies
    common = frozenset(reqs_for_extra(None))
  File "/tmp/tmplP35TH/distribute-0.6.34/pkg_resources.py", line 2494, in reqs_for_extra
    if req.marker_fn(override={'extra':extra}):
  File "/tmp/tmplP35TH/distribute-0.6.34/_markerlib/markers.py", line 109, in marker_fn
    return eval(compiled_marker, environment)
  File "<environment marker>", line 1, in <module>
NameError: name 'sys_platform' is not defined
Something went wrong during the installation.
See the error message above.
[[ERROR]] Installing distribute which should deliver easy_install failed?
```

I don't know where to continue from here. Can you help? What output do you need?

**Comment by Louwrensth** [comment] 2015-01-29 13:42
Hi again,

Update: I gave up and tried again. The system that I'm using seems unreliable (the more reason for deploying easybuild here!). 

I tried again from scratch, with a local installation of a statically built python 2.7.9 and an installation of environment modules (Tcl 1.578 version). I was able to run the bootstrap_eb.py script. 

But it was picking up an outdated modulecmd installation (3.2.8<3.2.10 required) instead of the new modulecmd.tcl I installed. 

I patched the bootstap_eb.py script to make it work:
```
# replace order of discovery: first modulecmd.tcl
sed -i "s@'modulecmd', 'lmod', 'modulecmd.tcl'@'modulecmd.tcl', 'lmod', 'modulecmd'@" bootstrap_eb.py
# change the match pattern to discover successful output of modulecmd.tcl
sed -i "s@modcmd_re = re.compile(.*)@modcmd_re = re.compile('Usage: module ')@" bootstrap_eb.py
```

The output of modulecmd.tcl wasn't matched by the original pattern. Compare the output for reference:
```
bash-3.2$ modulecmd python help 2>&1 |head -n4

  Modules Release 3.2.8 2010-10-01 (Copyright GNU GPL v2 1991):

  Usage: module [ switches ] [ subcommand ] [subcommand-args ]
bash-3.2$ modulecmd.tcl python help 2>&1 |head -n2
Modules Release Tcl 1.578         Copyright GNU GPL v2 1991
Usage: module [options] [command] [args ...]
```

**Comment by boegel** [comment] 2015-01-30 12:33
@Louwrensth: if you tell EasyBuild to use the Tcl-only version of environment modules, it will not pick up `modulecmd` automatically when installing EasyBuild with EasyBuild, so it shouldn't complain about v3.2.10: `export EASYBUILD_MODULES_TOOL=EnvironmentModulesTcl` (see http://easybuild.readthedocs.org/en/latest/Configuration.html#modules-tool-modules-tool)

the original regex `module\s.*command\s` should also match the output of your `modulecmd.tcl`, right? so there's no need to change the regex?

EasyBuild has support for Tcl-only environment modules (i.e. `modulecmd.tcl`), but it's certainly not tested as well as support for `modulecmd` or `lmod` is, so I'd love to hear more details to fix the issues you may be having...

Unless you're stuck to Tcl-only environment modules, I would warmly recommend looking into Lmod.

**Comment by Louwrensth** [comment] 2015-01-30 12:48
@boegel Thanks for you reply. I will try the EnvironmentModulesTcl option next time for installing EasyBuild with EasyBuild. I got two but's:

But note, here I was installing EasyBuild using the bootstrap_eb.py script, which I believe will ignore this environment variable.

But also I'm quite sure that the original regex did not work for modulecmd.tcl, as it was not picked after changing the order of disovering modulecmd from the $PATH. The offending bit is the one \s at the end of the regex, the Tcl version has a slightly different output:
'''
$ modulecmd.tcl python help 2>&1 | sed '/module\s.*command\s/!d'
$ modulecmd.tcl python help 2>&1 | sed '/module\s.*command/!d'
Usage: module [options] [command] [args ...]
'''
Testing that the new regex also works for the C/Tcl version: (I don't  know about Lmod)
'''
$ modulecmd python help 2>&1 | sed '/module\s.*command/!d'
  Usage: module [ switches ] [ subcommand ] [subcommand-args ]
'''
I'll take a look into Lmod

**Comment by boegel** [comment] 2015-01-30 12:59
@Louwrensth: during the bootstrap, a 'manually' installed EasyBuild is used to install the final EasyBuild (stage 2), and that one will listen to `$EASYBUILD_MODULES_TOOL`

I'll recheck the regex, thanks for the details.

**Comment by verdurin** [comment] 2015-08-24 10:07
Here's what I see, on a Fedora 22 system:

```
[adam@hostname ~]$ python bootstrap_eb.py ~/.local/easybuild/
[[DEBUG]] Going to use /tmp/tmpaJofLg as temporary directory
[[DEBUG]] Output from modulecmd python help: sh: modulecmd: command not found

[[DEBUG]] Output from lmod python help: Usage: module [options] sub-command [args ...]

Options:
  -h -? -H --help                   This help message
  -s availStyle --style=availStyle  Site controlled avail style: system
                                    (default: system)
  -D                                Program tracing written to stderr
  --debug=dbglvl                    Program tracing written to stderr
  --pin_versions=pinVersions        When doing a restore use specified
                                    version, do not follow defaults
  -d --default                      List default modules only when used with
                                    avail
  -q --quiet                        Do not print out warnings
  --topic=topic                     help topics: modfuncs envvars
  --expert                          Expert mode
  -t --terse                        Write out in machine readable format for
                                    commands: list, avail, spider, savelist
  --initial_load                    loading Lmod for first time in a user
                                    shell
  --latest                          Load latest (ignore default)
  --ignore_cache                    Treat the cache file(s) as out-of-date
  --novice                          Turn off expert and quiet flag
  --raw                             Print modulefile in raw output when used
                                    with show
  -w twidth --width=twidth          Use this as max term width
  -v --version                      Print version info and quit
  -r --regexp                       use regular expression match
  --gitversion                      Dump git version in a machine readable
                                    way and quit
  --dumpversion                     Dump version in a machine readable way
                                    and quit
  --localvar=localvarA              local variables needed to be set after
                                    this commands execution
  --check_syntax --checkSyntax      Checking module command syntax: do not
                                    load
  --config                          Report Lmod Configuration
  --mt                              Report Module Table State
  --timer                           report run times
  --force                           force removal of a sticky module or save
                                    an empty collection
  --redirect                        Send the output of list, avail, spider
                                    to stdout (not stderr)
  --no_redirect                     Force output of list, avail and spider
                                    to stderr
  --show_hidden                     Avail and spider will report hidden
                                    modules
  --spider_timeout=timeout          a timeout for spider


module [options] sub-command [args ...]

Help sub-commands:
------------------
  help                              prints this message
  help                module [...]  print help message from module(s)

Loading/Unloading sub-commands:
-------------------------------
  load | add          module [...]  load module(s)
  try-load | try-add  module [...]  Add module(s), do not complain if not
                                    found
  del | unload        module [...]  Remove module(s), do not complain if not
                                    found
  swap | sw | switch  m1 m2         unload m1 and load m2
  purge                             unload all modules
  refresh                           reload aliases from current list of
                                    modules.
  update                            reload all currently loaded modules.

Listing / Searching sub-commands:
---------------------------------
  list                              List loaded modules
  list                s1 s2 ...     List loaded modules that match the
                                    pattern
  avail | av                        List available modules
  avail | av          string        List available modules that contain
                                    "string".
  spider                            List all possible modules
  spider              module        List all possible version of that module
                                    file
  spider              string        List all module that contain the
                                    "string".
  spider              name/version  Detailed information about that version
                                    of the module.
  whatis              module        Print whatis information about module
  keyword | key       string        Search all name and whatis that contain
                                    "string".

Searching with Lmod:
--------------------
  All searching (spider, list, avail, keyword) support regular expressions:

  spider -r           '^p'          Finds all the modules that start with
                                    `p' or `P'
  spider -r           mpi           Finds all modules that have "mpi" in
                                    their name.
  spider -r           'mpi$         Finds all modules that end with "mpi" in
                                    their name.

Handling a collection of modules:
--------------------------------
  save | s                          Save the current list of modules to a
                                    user defined "default".
  save | s            name          Save the current list of modules to
                                    "name" collection.
  restore | r                       Restore modules from the user's
                                    "default" or system default.
  restore | r         name          Restore modules from "name" collection.
  restore             system        Restore module state to system defaults.
  savelist                          List of saved collections.

Deprecated commands:
--------------------
  reset                             The same as "restore system"
  getdefault          [name]        load name collection of modules or
                                    user's "default" if no name given.
                                    ===> Use "restore" instead <====
  setdefault          [name]        Save current list of modules to name if
                                    given, otherwise save as the default
                                    list for you the user.
                                    ===> Use "save" instead. <====

Miscellaneous sub-commands:
---------------------------
  show                modulefile    show the commands in the module file.
  use [-a]            path          Prepend or Append path to MODULEPATH.
  unuse               path          remove path from MODULEPATH.
  tablelist                         output list of active modules as a lua
                                    table.

Important Environment Variables:
--------------------------------
  LMOD_COLORIZE                     If defined to be "YES" then Lmod prints
                                    properties and warning in color.

    --------------------------------------------------------------------------

The following guides are at http://www.tacc.utexas.edu/tacc-projects/lmod

  User Guide                 - How to use.
  Advance User Guide         - How to create you own modules.
  System Administrator Guide - How to install Lmod on your own system.
    --------------------------------------------------------------------------



Modules based on Lua: Version 5.9.4.2  2015-05-18 16:35
    by Robert McLay mclay@tacc.utexas.edu

os.environ["LMOD_DEFAULT_MODULEPATH"] = "/etc/modulefiles:/usr/share/modulefiles:/usr/share/Modules/modulefiles";
os.environ["MODULEPATH"] = "/etc/modulefiles:/usr/share/modulefiles:/usr/share/Modules/modulefiles";
os.environ["LMOD_DEFAULT_MODULEPATH"] = "/etc/modulefiles:/usr/share/modulefiles:/usr/share/Modules/modulefiles";
os.environ["MODULEPATH"] = "/etc/modulefiles:/usr/share/modulefiles:/usr/share/Modules/modulefiles";
os.environ["_ModuleTable001_"] = "X01vZHVsZVRhYmxlXz17WyJhY3RpdmVTaXplIl09MCxiYXNlTXBhdGhBPXsiL2V0Yy9tb2R1bGVmaWxlcyIsIi91c3Ivc2hhcmUvbW9kdWxlZmlsZXMiLCIvdXNyL3NoYXJlL01vZHVsZXMvbW9kdWxlZmlsZXMiLH0sWyJjX3JlYnVpbGRUaW1lIl09ZmFsc2UsWyJjX3Nob3J0VGltZSJdPWZhbHNlLGZhbWlseT17fSxpbmFjdGl2ZT17fSxtVD17fSxtcGF0aEE9eyIvZXRjL21vZHVsZWZpbGVzIiwiL3Vzci9zaGFyZS9tb2R1bGVmaWxlcyIsIi91c3Ivc2hhcmUvTW9kdWxlcy9tb2R1bGVmaWxlcyIsfSxbInN5c3RlbUJhc2VNUEFUSCJdPSIvZXRjL21vZHVsZWZpbGVzOi91c3Ivc2hhcmUvbW9kdWxlZmlsZXM6L3Vzci9zaGFyZS9Nb2R1bGVzL21vZHVsZWZpbGVzIixbInZlcnNp";
os.environ["_ModuleTable002_"] = "b24iXT0yLH0=";
os.environ["_ModuleTable_Sz_"] = "2";

[[INFO]] Found module command 'lmod' (Lmod), so using it.
[[DEBUG]] sys.path after cleaning: ['/home/adam', '/usr/lib64/python27.zip', '/usr/lib64/python2.7', '/usr/lib64/python2.7/plat-linux2', '/usr/lib64/python2.7/lib-tk', '/usr/lib64/python2.7/lib-old', '/usr/lib64/python2.7/lib-dynload', '/usr/lib64/python2.7/site-packages', '/usr/lib64/python2.7/site-packages/gtk-2.0', '/usr/lib/python2.7/site-packages']
[[INFO]] 

+++ STAGE 0: installing distribute via included (patched) distribute_setup.py...


[[DEBUG]] preparing environment...
[[DEBUG]] Preparing for path /tmp/tmpaJofLg
[[DEBUG]] os.environ['PYTHONPATH'] after reset: 
[[DEBUG]] $EASYBUILD_MODULES_TOOL set to Lmod
[[DEBUG]] distribute_setup.__file__: /tmp/tmpaJofLg/distribute_setup.py
Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.34.tar.gz
Extracting in /tmp/tmprcb6GL
Now working in /tmp/tmprcb6GL/distribute-0.6.34
Installing Distribute
Before install bootstrap.
Scanning installed packages
Setuptools installation detected at /usr/lib/python2.7/site-packages
Not patching, --root or --prefix is installing Distribute in another location
Traceback (most recent call last):
  File "setup.py", line 248, in <module>
    scripts = scripts,
  File "/usr/lib64/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "/tmp/tmprcb6GL/distribute-0.6.34/setuptools/dist.py", line 225, in __init__
    _Distribution.__init__(self,attrs)
  File "/usr/lib64/python2.7/distutils/dist.py", line 287, in __init__
    self.finalize_options()
  File "/tmp/tmprcb6GL/distribute-0.6.34/setuptools/dist.py", line 257, in finalize_options
    ep.require(installer=self.fetch_build_egg)
  File "/tmp/tmprcb6GL/distribute-0.6.34/pkg_resources.py", line 2025, in require
    working_set.resolve(self.dist.requires(self.extras),env,installer))
  File "/tmp/tmprcb6GL/distribute-0.6.34/pkg_resources.py", line 2235, in requires
    dm = self._dep_map
  File "/tmp/tmprcb6GL/distribute-0.6.34/pkg_resources.py", line 2464, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/tmp/tmprcb6GL/distribute-0.6.34/pkg_resources.py", line 2497, in _compute_dependencies
    common = frozenset(reqs_for_extra(None))
  File "/tmp/tmprcb6GL/distribute-0.6.34/pkg_resources.py", line 2494, in reqs_for_extra
    if req.marker_fn(override={'extra':extra}):
  File "/tmp/tmprcb6GL/distribute-0.6.34/_markerlib/markers.py", line 109, in marker_fn
    return eval(compiled_marker, environment)
  File "<environment marker>", line 1, in <module>
NameError: name 'sys_platform' is not defined
Something went wrong during the installation.
See the error message above.
[[ERROR]] Installing distribute which should deliver easy_install failed?

[adam@hostname ~]$ rpm -q python python-setuptools
python-2.7.10-4.fc22.x86_64
python-setuptools-17.1.1-3.fc22.noarch

**Comment by boegel** [comment] 2015-10-06 17:29
@wpoely86: since you have Fedora 22 too, can you see if you can reproduce this?
Maybe installing/using an old distribute (like the bootstrap does in stage 0) is just a non-go on very recent systems for some reason...

**Comment by wpoely86** [comment] 2015-10-07 07:59
I got:
```
$ python bootstrap_eb.py ~/.local/easybuild-test/
[[INFO]] Found module command 'modulecmd' (EnvironmentModulesC), so using it.
[[INFO]] 

+++ STAGE 0: installing distribute via included (patched) distribute_setup.py...


Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.34.tar.gz
Extracting in /tmp/tmp_ShC53
Now working in /tmp/tmp_ShC53/distribute-0.6.34
Installing Distribute
Something went wrong during the installation.
See the error message above.
[[ERROR]] Installing distribute which should deliver easy_install failed?
```

**Comment by wpoely86** [comment] 2015-10-07 08:00
Now with the actual debug logs:
```
$ python bootstrap_eb.py ~/.local/easybuild-test/
[[DEBUG]] Going to use /tmp/tmppjk2RG as temporary directory
[[DEBUG]] Output from modulecmd python help: 
  Modules Release 3.2.10 2012-12-21 (Copyright GNU GPL v2 1991):

  Usage: module [ switches ] [ subcommand ] [subcommand-args ]

Switches:
	-H|--help		this usage info
	-V|--version		modules version & configuration options
	-f|--force		force active dependency resolution
	-t|--terse		terse    format avail and list format
	-l|--long		long     format avail and list format
	-h|--human		readable format avail and list format
	-v|--verbose		enable  verbose messages
	-s|--silent		disable verbose messages
	-c|--create		create caches for avail and apropos
	-i|--icase		case insensitive
	-u|--userlvl <lvl>	set user level to (nov[ice],exp[ert],adv[anced])
  Available SubCommands and Args:
	+ add|load		modulefile [modulefile ...]
	+ rm|unload		modulefile [modulefile ...]
	+ switch|swap		[modulefile1] modulefile2
	+ display|show		modulefile [modulefile ...]
	+ avail			[modulefile [modulefile ...]]
	+ use [-a|--append]	dir [dir ...]
	+ unuse			dir [dir ...]
	+ update
	+ refresh
	+ purge
	+ list
	+ clear
	+ help			[modulefile [modulefile ...]]
	+ whatis		[modulefile [modulefile ...]]
	+ apropos|keyword	string
	+ initadd		modulefile [modulefile ...]
	+ initprepend		modulefile [modulefile ...]
	+ initrm		modulefile [modulefile ...]
	+ initswitch		modulefile1 modulefile2
	+ initlist
	+ initclear


[[INFO]] Found module command 'modulecmd' (EnvironmentModulesC), so using it.
[[DEBUG]] sys.path after cleaning: ['/home/ward/tmp/easybuild-framework/easybuild/scripts', '/usr/lib64/python27.zip', '/usr/lib64/python2.7', '/usr/lib64/python2.7/plat-linux2', '/usr/lib64/python2.7/lib-tk', '/usr/lib64/python2.7/lib-old', '/usr/lib64/python2.7/lib-dynload', '/usr/lib64/python2.7/site-packages', '/usr/lib64/python2.7/site-packages/gst-0.10', '/usr/lib64/python2.7/site-packages/gtk-2.0', '/usr/lib/python2.7/site-packages']
[[INFO]] 

+++ STAGE 0: installing distribute via included (patched) distribute_setup.py...


[[DEBUG]] preparing environment...
[[DEBUG]] Preparing for path /tmp/tmppjk2RG
[[DEBUG]] os.environ['PYTHONPATH'] after reset: 
[[DEBUG]] $EASYBUILD_MODULES_TOOL set to EnvironmentModulesC
[[DEBUG]] distribute_setup.__file__: /tmp/tmppjk2RG/distribute_setup.py
Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.34.tar.gz
Extracting in /tmp/tmpqwoKTu
Now working in /tmp/tmpqwoKTu/distribute-0.6.34
Installing Distribute
Before install bootstrap.
Scanning installed packages
Setuptools installation detected at /usr/lib/python2.7/site-packages
Not patching, --root or --prefix is installing Distribute in another location
Traceback (most recent call last):
  File "setup.py", line 248, in <module>
    scripts = scripts,
  File "/usr/lib64/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "/tmp/tmpqwoKTu/distribute-0.6.34/setuptools/dist.py", line 225, in __init__
    _Distribution.__init__(self,attrs)
  File "/usr/lib64/python2.7/distutils/dist.py", line 287, in __init__
    self.finalize_options()
  File "/tmp/tmpqwoKTu/distribute-0.6.34/setuptools/dist.py", line 257, in finalize_options
    ep.require(installer=self.fetch_build_egg)
  File "/tmp/tmpqwoKTu/distribute-0.6.34/pkg_resources.py", line 2025, in require
    working_set.resolve(self.dist.requires(self.extras),env,installer))
  File "/tmp/tmpqwoKTu/distribute-0.6.34/pkg_resources.py", line 2235, in requires
    dm = self._dep_map
  File "/tmp/tmpqwoKTu/distribute-0.6.34/pkg_resources.py", line 2464, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/tmp/tmpqwoKTu/distribute-0.6.34/pkg_resources.py", line 2497, in _compute_dependencies
    common = frozenset(reqs_for_extra(None))
  File "/tmp/tmpqwoKTu/distribute-0.6.34/pkg_resources.py", line 2494, in reqs_for_extra
    if req.marker_fn(override={'extra':extra}):
  File "/tmp/tmpqwoKTu/distribute-0.6.34/_markerlib/markers.py", line 109, in marker_fn
    return eval(compiled_marker, environment)
  File "<environment marker>", line 1, in <module>
NameError: name 'sys_platform' is not defined
Something went wrong during the installation.
See the error message above.
[[ERROR]] Installing distribute which should deliver easy_install failed?
```

**Comment by boegel** [comment] 2015-10-07 08:05
OK, so the problem is easily reproducible...

We'll need to figure out a fix for this.

Maybe we should try falling back to the system's `easy_install` if stage 0 fails?

**Comment by boegel** [comment] 2015-10-29 20:15
A proper solution for this is probably to bump the version of distribute being installed by the bootstrap in stage 0 to something more recent...

Up for giving that a try @wpoely86 (not super urgent imho, moving this to the 2.5.0 milestone).

**Comment by boegel** [comment] 2015-11-27 14:36
Fixed in https://github.com/hpcugent/easybuild-framework/pull/1490, thanks @wpoely86!

**Comment by boegel** [comment] 2015-11-27 14:37
@Louwrensth: please retest with updated bootstrap script (just redownload from same location)

**Closed by boegel** 2015-11-27 14:37 UTC
