### ISSUE TITLE
Issues with substitution in robot_paths

### ISSUE THREAD

**Issue by wpoely86** [hpcugent/easybuild-framework#1216] opened 2015-03-11 14:55 UTC
In the `config.cfg`:
```
robot-paths=%(repositorypath)s:%(DEFAULT_ROBOT_PATHS)s
```
gives (with 103a730004ba):
```
$ eb -d HDF5.eb
Traceback (most recent call last):
  File "/home/ward/opt/lib/python2.7/site-packages/easybuild_framework-2.1.0dev-py2.7.egg/easybuild/main.py", line 338, in <module>
    main()
  File "/home/ward/opt/lib/python2.7/site-packages/easybuild_framework-2.1.0dev-py2.7.egg/easybuild/main.py", line 157, in main
    eb_go = eboptions.parse_options(args=args)
  File "/home/ward/opt/lib/python2.7/site-packages/easybuild_framework-2.1.0dev-py2.7.egg/easybuild/tools/options.py", line 646, in parse_options
    go_args=args)
  File "/home/ward/opt/lib/python2.7/site-packages/easybuild_framework-2.1.0dev-py2.7.egg/easybuild/tools/options.py", line 105, in __init__
    super(EasyBuildOptions, self).__init__(*args, **kwargs)
  File "/home/ward/opt/lib/python2.7/site-packages/vsc_base-2.0.4-py2.7.egg/vsc/utils/generaloption.py", line 763, in __init__
    self.parseconfigfiles()
  File "/home/ward/opt/lib/python2.7/site-packages/vsc_base-2.0.4-py2.7.egg/vsc/utils/generaloption.py", line 1168, in parseconfigfiles
    for opt, val in self.configfile_parser.items(section):
  File "/usr/lib64/python2.7/ConfigParser.py", line 655, in items
    for option in options]
  File "/usr/lib64/python2.7/ConfigParser.py", line 691, in _interpolate
    self._interpolate_some(option, L, rawval, section, vars, 1)
  File "/usr/lib64/python2.7/ConfigParser.py", line 723, in _interpolate_some
    option, section, rest, var)
ConfigParser.InterpolationMissingOptionError: Bad value substitution:
	section: [basic]
	option : robot-paths
	key    : repositorypath
	rawval : :%(DEFAULT_ROBOT_PATHS)s

```

**Comment by boegel** [comment] 2015-03-11 16:16
Hmm, I'm not able to reproduce this in the tests... Anything else going on? What does the full configuration file look like?

```diff                   
diff --git a/test/framework/config.py b/test/framework/config.py
index c0959b4..c1dfaa6 100644
--- a/test/framework/config.py
+++ b/test/framework/config.py
@@ -213,7 +213,8 @@ class EasyBuildConfigTest(EnhancedTestCase):
         cfgtxt = '\n'.join([
             '[config]',
             'buildpath = %s' % testpath1,
-            'robot-paths = /tmp/foo:%(DEFAULT_ROBOT_PATHS)s',
+            'repositorypath = /tmp/ebrepo',
+            'robot-paths=/tmp/foo:%(repositorypath)s:%(DEFAULT_ROBOT_PATHS)s',
         ])
         write_file(config_file, cfgtxt)
 
@@ -227,8 +228,7 @@ class EasyBuildConfigTest(EnhancedTestCase):
         self.assertEqual(install_path(), os.path.join(os.getenv('HOME'), '.local', 'easybuild', 'software'))  # default
         self.assertEqual(source_paths(), [testpath2])  # via command line
         self.assertEqual(build_path(), testpath1)  # via config file
-        self.assertTrue('/tmp/foo' in options.robot_paths)
-        self.assertTrue(os.path.join(tmpdir, 'easybuild', 'easyconfigs') in options.robot_paths)
+        self.assertEqual(options.robot_paths[:3], ['/tmp/foo', '/tmp/ebrepo', os.path.join(tmpdir, 'easybuild', 'easyconfigs')])
 
         testpath3 = os.path.join(self.tmpdir, 'testTHREE')
         os.environ['EASYBUILD_SOURCEPATH'] = testpath2
```

```
$ python -m test.framework.config
.......
----------------------------------------------------------------------
Ran 7 tests in 4.597s

OK
```

**Comment by wpoely86** [comment] 2015-03-11 16:19
The full config: https://gist.github.com/c0201257a11409be8cd8
No env vars set.

Debug output: https://gist.github.com/d5ba6be099a02488f522

**Comment by boegel** [comment] 2015-03-11 16:21
You don't have `repositorypath` defined, that's the problem.

**Comment by wpoely86** [comment] 2015-03-11 16:23
OK, I was expecting that the default `repositorypath` would be used...

**Comment by wpoely86** [comment] 2015-03-11 16:26
Maybe we should add something like `DEFAULT_REPOSITORYPATH`? Then we can just set,
```
robot-paths=%(DEFAULT_REPOSITORYPATH)s:%(DEFAULT_ROBOT_PATHS)s
```
and don't look back.

**Comment by boegel** [comment] 2015-03-11 20:41
updated docs @ https://github.com/hpcugent/easybuild/pull/103

I'll look into support for `DEFAULT_REPOSITORYPATH` too, should be fairly trivial.

**Comment by boegel** [comment] 2015-03-12 14:19
support for `%(DEFAULT_REPOSITORYPATH)s` in #1220, closing this

**Closed by boegel** 2015-03-12 14:19 UTC
