### ISSUE TITLE
python -m test.framework.suite FAILED (failures=2, errors=1) on CentOS 7.2

### ISSUE THREAD

**Issue by OleHolmNielsen** [hpcugent/easybuild-framework#1849] opened 2016-07-18 14:07 UTC
```
ERROR: test_toy_dumped_easyconfig (test.framework.toy_build.ToyBuildTest)
## Test dumping of file in eb_filerepo in both .eb and .yeb format

Traceback (most recent call last):
  File "/home/opt/modules/software/EasyBuild/2.8.2/lib/python2.7/site-packages/easybuild_framework-2.8.2-py2.7.egg/test/framework/toy_build.py", line 1149, in test_toy_dumped_easyconfig
    ec = EasyConfig(args[0])
  File "/home/opt/modules/software/EasyBuild/2.8.2/lib/python2.7/site-packages/easybuild_framework-2.8.2-py2.7.egg/easybuild/framework/easyconfig/easyconfig.py", line 256, in **init**
    raise EasyBuildError("EasyConfig **init** expected a valid path")
EasyBuildError: 'EasyConfig **init** expected a valid path'
```

```
FAIL: test_environment_command (test.framework.modulestool.ModulesToolTest)
## Test setting cmd via enviroment

Traceback (most recent call last):
  File "/home/opt/modules/software/EasyBuild/2.8.2/lib/python2.7/site-packages/easybuild_framework-2.8.2-py2.7.egg/test/framework/modulestool.py", line 108, in test_environment_command
    self.assertEqual(bmmt.cmd, cmd_abspath)
  File "/home/opt/modules/software/EasyBuild/2.8.2/lib/python2.7/site-packages/vsc_install-0.10.11-py2.7.egg/vsc/install/testing.py", line 79, in assertEqual
    raise AssertionError("%s:\nDIFF%s:\n%s" % (msg, limit, ''.join(diff[:self.ASSERT_MAX_DIFF])))
AssertionError: '/usr/bin/echo' != '/bin/echo':
DIFF:
- /usr/bin/echo? ----
```

```
FAIL: test_mock (test.framework.modulestool.ModulesToolTest)
## Test the mock module

Traceback (most recent call last):
  File "/home/opt/modules/software/EasyBuild/2.8.2/lib/python2.7/site-packages/easybuild_framework-2.8.2-py2.7.egg/test/framework/modulestool.py", line 88, in test_mock
    self.assertEqual(mmt.cmd, cmd_abspath)
  File "/home/opt/modules/software/EasyBuild/2.8.2/lib/python2.7/site-packages/vsc_install-0.10.11-py2.7.egg/vsc/install/testing.py", line 79, in assertEqual
    raise AssertionError("%s:\nDIFF%s:\n%s" % (msg, limit, ''.join(diff[:self.ASSERT_MAX_DIFF])))
AssertionError: '/usr/bin/echo' != '/bin/echo':
DIFF:
- /usr/bin/echo? ----
```

```
---
# System information

OS: CentOS 7.2

[modules@sylg ~]$ python -V
Python 2.7.5
[modules@sylg ~]$ type module
module is a function
module () 
{ 
    eval $($LMOD_CMD bash "$@");
    [ $? = 0 ] && eval $(${LMOD_SETTARG_CMD:-:} -s sh)
}
[modules@sylg ~]$ type -f module
-bash: type: module: not found
[modules@sylg ~]$ module --version

Modules based on Lua: Version 6.3.4  2016-05-11 17:00
    by Robert McLay mclay@tacc.utexas.edu

[modules@sylg ~]$ module av EasyBuild

--------------------------------------------------------------------------------------------------------------- /home/opt/modules/modules/all ----------------------------------------------------------------------------------------------------------------
   EasyBuild/2.8.2 (L)

  Where:
   L:  Module is loaded

Use "module spider" to find all possible modules.
Use "module keyword key1 key2 ..." to search for all possible modules matching any of the "keys".

[modules@sylg ~]$ which -a eb
~/software/EasyBuild/2.8.2/bin/eb
[modules@sylg ~]$ eb --version
This is EasyBuild 2.8.2 (framework: 2.8.2, easyblocks: 2.8.2) on host sylg.fysik.dtu.dk.
```

**Comment by geimer** [comment] 2016-07-25 11:50
Looks like a duplicate of #1848

**Comment by boegel** [comment] 2016-11-12 21:48
@OleHolmNielsen Like I said in #1848, let's revisit this after the EasyBuild v3.0 release, these issues are very likely just problems with the tests themselves.

**Comment by boegel** [comment] 2016-12-16 08:52
follow-up in #1848

**Closed by boegel** 2016-12-16 08:52 UTC
