### ISSUE TITLE
cannot import name GENERAL_CLASS

### ISSUE THREAD

**Issue by foxik0070** [hpcugent/easybuild-framework#2117] opened 2017-02-13 08:39 UTC
Hello,

After install EasyBuild new version (3.1.0) we see this error, any advice?

$ eb
Traceback (most recent call last):
   File "/usr/lib64/python2.6/runpy.py", line 122, in _run_module_as_main
     "__main__" Fname, loader, pkg_name)
   File "/usr/lib64/python2.6/runpy.py", line 34, in _run_code
     exec code in run_globals
   File "/apps/all/EasyBuild/3.1.0/lib/python2.6/site-packages/easybuild_framework-3.1.0-py2.6.egg/easybuild/main.py", line 49, in <module>
     import easybuild.tools.config as config
   File "/apps/all/EasyBuild/3.1.0/lib/python2.6/site-packages/easybuild_framework-3.1.0-py2.6.egg/easybuild/tools/config.py", line 48, in <module >
     easybuild.tools.module_naming_scheme from import GENERAL_CLASS
ImportError: can not import name GENERAL_CLASS

thank you ...
LK

**Comment by boegel** [comment] 2017-02-13 09:10
@foxik0070 How did you install EasyBuild v3.1.0? Did you have another EasyBuild version installed earlier? What does this print?

```shell
echo $PYTHONPATH
python -c "import easybuild; print easybuild.__file__; import easybuild.tools; print easybuild.tools.__file__"
```

**Comment by foxik0070** [comment] 2017-02-13 09:15
@boegel Installed from EasyBuild-3.1.0.eb, but this is develop version. Yes, we have older versions (2.1.1  2.2.0  2.3.0  2.4.0  2.5.0  2.7.0  2.8.0  2.9.0  3.0.0  3.0.1.lua  3.0.2.lua  3.1.0.lua) and last instalation not working.

Print:
~]$ echo $PYTHONPATH
/apps/all/EasyBuild/3.1.0/lib/python2.6/site-packages::/apps/easybuild/python

~]$ python -c "import easybuild; print easybuild.__file__; import easybuild.tools; print easybuild.tools.__file__"
/apps/easybuild/python/easybuild/__init__.pyc
/apps/easybuild/python/easybuild/tools/__init__.py

**Comment by boegel** [comment] 2017-02-13 09:25
@foxik0070 Python is picking up the installation you have in `/apps/easybuild/python`, which seems to be older?

How was this installation performed, and what is there exactly?

If you remove `/apps/easybuild/python` from `$PYTHONPATH`, the problem should be fixed?

**Comment by foxik0070** [comment] 2017-02-13 09:31
@boegel Yes, I am removed `/apps/easybuild/python` from the path and now it's work. Thank you.
And installation is the same as the older versions.

**Comment by boegel** [comment] 2017-02-13 09:44
@foxik0070 If the problem is fixed now, please close this issue.

**Closed** 2017-02-13 09:46 UTC
