### ISSUE TITLE
Install failed due to error with PYTHONPATH

### ISSUE THREAD

**Issue by koallen** [hpcugent/easybuild-framework#2116] opened 2017-02-13 06:45 UTC
I'm trying to install Easybuild on CentOS 7.2 with system default `python` & `gcc`. I'm using the bootstrap script provided in the `master` branch. State 1 goes well, but I encountered errors at `installing...` step of stage 2.

The error is

```
== FAILED: Installation ended unsuccessfully (build directory: /tmp/tmpyPFaWx/EasyBuild/3.1.0/dummy-dummy): build failed (first 300 chars): cmd "/usr/bin/python $(which easy_install) -U --prefix /home/siyuan/.local/easybuild/software/EasyBuild/3.1.0 vsc-install &&  /usr/bin/python setup.py install --prefix=/home/siyuan/.local/easybuild/software/EasyBuild/3.1.0 " exited with exitcode 1 and output:
Creating /home/siyuan/.local/easybuild/s
== Results of the build can be found in the log file(s) /tmp/eb-Y3uaVa/easybuild-EasyBuild-3.1.0-20170213.143359.KfVHV.log
Traceback (most recent call last):
  File "bootstrap_eb.py", line 970, in <module>
    main()
  File "bootstrap_eb.py", line 773, in main
    stage2(tmpdir, templates, install_path, distribute_egg_dir, sourcepath)
  File "bootstrap_eb.py", line 673, in stage2
    easybuild_main()
  File "/tmp/tmpyPFaWx/eb_stage1/lib/python2.7/site-packages/easybuild_framework-3.1.0-py2.7.egg/easybuild/main.py", line 422, in main
    ecs_with_res = build_and_install_software(ordered_ecs, init_session_state, exit_on_failure=exit_on_failure)
  File "/tmp/tmpyPFaWx/eb_stage1/lib/python2.7/site-packages/easybuild_framework-3.1.0-py2.7.egg/easybuild/main.py", line 151, in build_and_install_software
    raise EasyBuildError(test_msg)
easybuild.tools.build_log.EasyBuildError: 'Build of /tmp/tmpyPFaWx/EasyBuild-3.1.0.eb failed (err: \'build failed (first 300 chars): cmd "/usr/bin/python $(which easy_install) -U --prefix /home/siyuan/.local/easybuild/software/EasyBuild/3.1.0 vsc-install &&  /usr/bin/python setup.py install --prefix=/home/siyuan/.local/easybuild/software/EasyBuild/3.1.0 " exited with exitcode 1 and output:\\nCreating /home/siyuan/.local/easybuild/s\')'
```

I tried to run

```
/usr/bin/python $(which easy_install) -U --prefix /home/siyuan/.local/easybuild/software/EasyBuild/3.1.0 vsc-install
```

manually and the error seems to be

```
TEST FAILED: /home/siyuan/.local/easybuild/software/EasyBuild/3.1.0/lib/python2.7/site-packages does NOT support .pth files
error: bad install directory or PYTHONPATH

You are attempting to install a package to a directory that is not
on PYTHONPATH and which Python does not read ".pth" files from.  The
installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /home/siyuan/.local/easybuild/software/EasyBuild/3.1.0/lib/python2.7/site-packages

and your PYTHONPATH environment variable currently contains:

    ''

Here are some of your options for correcting the problem:

* You can choose a different installation directory, i.e., one that is
  on PYTHONPATH or supports .pth files

* You can add the installation directory to the PYTHONPATH environment
  variable.  (It must then also be on PYTHONPATH whenever you run
  Python and want to use the package(s) you are installing.)

* You can set up the installation directory to support ".pth" files by
  using one of the approaches described here:

  https://pythonhosted.org/setuptools/easy_install.html#custom-installation-locations

Please make the appropriate changes for your system and try again.
```

**Comment by koallen** [comment] 2017-02-13 07:20
Ok, I somehow got it working. Let me describe my procedure cause the documentation is a little bit confusing to me. This is what I did

- Install using bootstrap script and failed (see above)
- Re-login to clear previously set environment variables
- `sudo pip install -U setuptools vsc-install vsc-base`
- Download bootstrap script again
- Bootstrap complains about `vsc-base` (`Found another vsc.utils.fancylogger than expected`)
- `sudo pip uninstall vsc-base vsc-install`
- Install using bootstrap script again and succeeded

So I have the following questions:

- The requirements include `vsc-base`, however, the script will complain if I install this dependency beforehand.
- I think the only thing that changed between the 2 installations is `setuptools` (cause I used `pip install -U`), would this be the problem?

**Comment by naveau** [comment] 2017-02-14 13:08
I had the same `fancylogger` error during the install and I can confirm that `vsc-install` and `vsc-base` should not be installed by the user before the bootstrap. I replicate this behavior on a freshly installed CentOS-7-minimal :

As root :
* `yum install epel-release `
* `yum install Lmod`
* `yum install python2-pip`
* `pip install --upgrade pip`
* `pip install -U setuptools`
* Add this step if you want to reproduce the error : `pip install -U vsc-base vsc-install`

Relog to the machine as a user (reload Lmod config) :
* 'wget  https://raw.githubusercontent.com/hpcugent/easybuild-framework/develop/easybuild/scripts/bootstrap_eb.py'
* `chmod +x bootstrap_eb.py `
* `./bootstrap_eb.py .`

If you installed `vsc-base` and `vsc-install` you will have this error during the bootstrap :
```
[[ERROR]] Found another vsc.utils.fancylogger than expected: /usr/lib/python2.7/site-packages/vsc/utils/fancylogger.pyc
```
If not, the bootstrap run to completion with success.

Hope that helps

**Comment by boegel** [comment] 2017-02-14 19:39
You should indeed not install `vsc-install` or `vsc-base` yourself before bootstrapping.
The bootstrap script will install both, and will make very sure that the `vsc-install` and `vsc-base` that it installs are also actually being used (which may not be the case when they were installed previously system-wide or via `pip install --user`).

The original problem may be something related to `setuptools`, but it's hard to tell from the provided information. The `easy_install -U` command you fleshed out failed indeed, but only because `$PYTHONPATH` was not set correctly or because the target directory didn't exist yet (both of which *are* done by the bootstrap script).

If you can still replicate the original problem, please try bootstrapping after running `export EASYBUILD_BOOTSTRAP_DEBUG=1` to get more detailed information.

In any case, the procedure that worked (installing an updated version of `setuptools` system-wide and then bootstrapping EasyBuild) is the right approach.

If you have any more specific pointers w.r.t. improving the existing documentation, please share them (which sections/paragraphs are misleading or missing information, etc.).

**Comment by koallen** [comment] 2017-02-15 04:45
Hi @boegel,

Thanks for the reply. I'll try to replicate the error with `easy_install` again with `EASYBUILD_BOOTSTRAP_DEBUG=1` set. And see if the `setuptool` is causing the problem.

As for my suggestion on improving the documentation, there are 2 sections that describe the dependencies of EasyBuild on [this page](http://easybuild.readthedocs.io/en/latest/Installation.html). Although the requirement section gives people a good overview of what the dependencies are, if people don't read on to the dependencies section, they will miss the note saying

> vsc-base is installed automatically along with EasyBuild

Therefore, a user may install `vsc-base` and `vsc-install` before using the bootstrap script (like me), resulting in the error I showed above.

Also, since you mentioned that one could set the environment variable `EASYBUILD_BOOTSTRAP_DEBUG` for debugging errors, do you think a new sub-section should be added under `In case of installation issue` to tell people to use this variable to provide more useful information when they open an issue here?

**Comment by koallen** [comment] 2017-02-15 06:16
I tried to replicate the error with a fresh CentOS 7.2.1511 and `python-pip` (which installs setuptools 0.9.8) but failed. I don't think I explicitly upgraded setuptools before (on the machine that had the error). Therefore, it's probably not setuptools' fault. I'll investigate further into the issue and see if I can find anything.

**Comment by basvandervlies** [comment] 2017-02-27 15:51
I jsut tried to bootstrap it on debian wheezy and had the same error. To solve it I had to
 * install pip
 * pip install --upgrade setuptools

**Comment by boegel** [comment] 2017-06-22 07:11
@koallen Any updates on this?

**Comment by koallen** [comment] 2017-06-22 07:18
Hi, I'm still not sure what the problem is. I've had no problem when I tried to reproduce the error or installing Bootstrap on another machine running freshly installed CentOS 7.3.

**Comment by boegel** [comment] 2017-06-22 07:56
OK, thank you for the feedback @koallen. I'll close this issue since it can't be reproduced, but for future reference, I think it's quite likely this way due to an outdated `setuptools` installation (or a buggy one).

**Closed by boegel** 2017-06-22 07:56 UTC

**Comment by StanleyRogowski** [comment] 2019-01-18 13:12
Hey sorry for picking this thing up again but im just about to install a easybuild up on my CentOS7 i got some Promblems i've no idea how solve them
> VERSION="7 (Core)"
- [X] lmod 
- [X] lua
...

i have managed to get around the first issue
`[[ERROR]] Found another vsc.utils.fancylogger than expected: /usr/lib/python2.7/site-packages/vsc/utils/fancylogger.pyc`
with uninstalling ` vsc-install` and `vsc-base`

*** btw thats almost wrong in the [install guide](https://easybuild.readthedocs.io/en/latest/Installation.html?highlight=fancylogger#required-python-packages) (it is listed as required package)

BUT i dont get around the second Issue 
```
Traceback (most recent call last):
  File "bootstrap_eb.py", line 1084, in <module>
    main()
  File "bootstrap_eb.py", line 887, in main
    stage2(tmpdir, templates, install_path, distribute_egg_dir, sourcepath)
  File "bootstrap_eb.py", line 734, in stage2
    os.makedirs(modules_path)
  File "/usr/lib64/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib64/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib64/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)

OSError: [Errno 13] Permission denied: '/home/vagrant/easybuild/easybuild'
```

Yes it is on a Vagrant VM but the script should have all needed Permissions anyway.
```
-rw-r--r--. 1 root    root    48257 Jan 17 14:42 bootstrap_eb.py
```
The Script Version is from 12/01/2019 so it literally shouln't be outdated. 

Does anyone have a workaround for me?

Greedings

**Comment by boegel** [comment] 2019-01-18 13:31
@koallen `vsc-base` and `vsc-install` are indeed listed as required packages for EasyBuild 3.x, but the bootstrap script installs them too, and it makes sure that the installation is using those copies rather than something else (to avoid that the installation breaks later)

What are the permissions on that directory? `ls -ld /home/vagrant/easybuild/easybuild`?

**Comment by StanleyRogowski** [comment] 2019-01-18 13:41
```drwxr-xr-x.  2 root    root      29 Jan 17 14:41 easybuild```

Nice hint thank you.
I have created a new dir with the Vagrant user and restarted the Installation and you wont believe it but it worked.

Thank you.

**Comment by boegel** [comment] 2019-01-18 16:10
@StanleyRogowski Oh, I do believe you! ;)
