### ISSUE TITLE
Running unit tests:  ImportError: No module named install.testing

### ISSUE THREAD

**Issue by ukgeorge** [hpcugent/easybuild-framework#1657] opened 2016-03-07 19:05 UTC
Following the instructions here 
http://easybuild.readthedocs.org/en/latest/Installation.html

After running:

export TEST_EASYBUILD_MODULES_TOOL=Lmod
python -m test.framework.suite

I get the following output 
```
$ python -m test.framework.suite
Traceback (most recent call last):
  File "/usr/lib64/python2.6/runpy.py", line 122, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.6/runpy.py", line 34, in _run_code
    exec code in run_globals
  File "/home/steve-s/.local/easybuild/software/Core/EasyBuild/2.6.0/lib/python2.6/site-packages/easybuild_framework-2.6.0-py2.6.egg/test/framework/suite.py", line 56, in <module>
    import test.framework.asyncprocess as a
  File "/home/steve-s/.local/easybuild/software/Core/EasyBuild/2.6.0/lib/python2.6/site-packages/easybuild_framework-2.6.0-py2.6.egg/test/framework/asyncprocess.py", line 33, in <module>
    from test.framework.utilities import EnhancedTestCase
  File "/home/steve-s/.local/easybuild/software/Core/EasyBuild/2.6.0/lib/python2.6/site-packages/easybuild_framework-2.6.0-py2.6.egg/test/framework/utilities.py", line 39, in <module>
    from vsc.utils.testing import EnhancedTestCase as _EnhancedTestCase
  File "/home/steve-s/.local/easybuild/software/Core/EasyBuild/2.6.0/lib/python2.6/site-packages/vsc_base-2.4.18-py2.6.egg/vsc/utils/testing.py", line 33, in <module>
    from vsc.install.testing import TestCase as EnhancedTestCase
ImportError: No module named install.testing
```

**Comment by boegel** [comment] 2016-03-08 08:21
Hmm, this is weird...

For some reason, the `vsc-install` package was not installed...

Did you use the bootstrap script? When did you download it (and what MD5sum do you have for it)?

Can you share the output of these commands?

```
ls /home/steve-s/.local/easybuild/software/Core/EasyBuild/2.6.0/lib/python2.6/site-packages
cat /home/steve-s/.local/easybuild/software/Core/EasyBuild/2.6.0/lib/python2.6/site-packages/*.pth
python -c "import setuptools; print setuptools.__version__; print setuptools.__file__"
```

**Comment by ukgeorge** [comment] 2016-03-08 10:04
Thanks fore getting back to me. Yes, I used the boostrap. This is the output from a fresh install and
output from the above commands you asked me to run

`steve-s@wrk012 > EASYBUILD_PREFIX=$HOME/.local/easybuild
steve-s@wrk012 > curl -O https://raw.githubusercontent.com/hpcugent/easybuild-framework/develop/easybuild/scripts/bootstrap_eb.py
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 33578  100 33578    0     0   115k      0 --:--:-- --:--:-- --:--:--  121k

steve-s@wrk012 > PATH=`dirname $LMOD_CMD`:$PATH python bootstrap_eb.py $EASYBUILD_PREFIX
`
[[INFO]] Installation prefix /home/steve-s/.local/easybuild
[[INFO]] Found module command 'lmod' (Lmod), so using it.
[[INFO]] 

+++ STAGE 0: installing distribute via included (patched) distribute_setup.py...


Downloading http://hpcugent.github.io/easybuild/files/distribute-0.6.49-patched1.tar.gz
Extracting in /tmp/tmpXKsQxz
Now working in /tmp/tmpXKsQxz/distribute-0.6.49
Installing Distribute
[[INFO]] 

+++ STAGE 1: installing EasyBuild in temporary dir with easy_install...


[[INFO]] installing EasyBuild with 'easy_install --quiet --upgrade --prefix=/tmp/tmpPXpLWE/eb_stage1 easybuild'
Installing with setuptools.setup...
Installing version 2.6.0
warning: install_lib: 'build/lib' does not exist -- no Python modules to install
zip_safe flag not set; analyzing archive contents...
Installing with setuptools.setup...
Installing version 2.6.0 (API version 2)
Installing with setuptools.setup...
Installing version 2.6.0 (required versions: API >= 2)
Installing with setuptools.setup...
Installing version 2.6.0 (required versions: API >= 2, easyblocks >= 2.6)
warning: install_lib: 'build/lib' does not exist -- no Python modules to install
INFO: This is (based on) vsc.install.shared_setup 0.9.19
INFO: run_tests from base dir /tmp/easy_install-4KKbzW/vsc-base-2.4.18 (using executable /tmp/easy_install-4KKbzW/vsc-base-2.4.18/setup.py)
WARN: cleanup lib/vsc_base.egg-info
INFO: removing 'lib/vsc_base.egg-info' (and everything under it)
INFO: generated list: ['vsc', 'vsc.utils']
INFO: generated packages list: ['vsc', 'vsc.utils']
INFO: makesetupcfg set to True, (re)creating setup.cfg
INFO: found license /tmp/easy_install-4KKbzW/vsc-base-2.4.18/LICENSE with md5sum 5f30f0716dfdd0d91eb439ebec522ec2
INFO: Found license name LGPLv2+ and classifier License :: OSI Approved :: GNU Lesser General Public License v2 or later (LGPLv2+)
INFO: setting license LGPLv2+
INFO: No name defined, trying to determine it
INFO: found match url https://github.com/hpcugent/vsc-base in /tmp/easy_install-4KKbzW/vsc-base-2.4.18/PKG-INFO
INFO: found match name vsc-base in /tmp/easy_install-4KKbzW/vsc-base-2.4.18/PKG-INFO
INFO: Removing None download_url
INFO: get_name_url returns {'url': 'https://github.com/hpcugent/vsc-base', 'name': 'vsc-base'}
INFO: using long_description Common tools used within our organization. Originally created by the HPC team of Ghent University (http://ugent.be/hpc).
INFO: generated list: ['bin/startlogdaemon.sh', 'bin/logdaemon.py', 'bin/optcomplete.bash']
INFO: generated scripts list: ['bin/startlogdaemon.sh', 'bin/logdaemon.py', 'bin/optcomplete.bash']
INFO: Checking .pth file support in .
INFO: /usr/bin/python -E -c pass
INFO: Searching for vsc-install>=0.9.19
INFO: Reading http://pypi.python.org/simple/vsc-install/
INFO: Best match: vsc-install 0.9.19
INFO: Downloading https://pypi.python.org/packages/source/v/vsc-install/vsc-install-0.9.19.tar.gz#md5=db8c042144fe59acce6d5ba61693ff4f
INFO: Processing vsc-install-0.9.19.tar.gz
INFO: Writing /tmp/easy_install-4KKbzW/vsc-base-2.4.18/temp/easy_install-pdMQNo/vsc-install-0.9.19/setup.cfg
INFO: Running vsc-install-0.9.19/setup.py -q bdist_egg --dist-dir /tmp/easy_install-4KKbzW/vsc-base-2.4.18/temp/easy_install-pdMQNo/vsc-install-0.9.19/egg-dist-tmp-IApcB9
INFO: This is (based on) vsc.install.shared_setup 0.9.19
INFO: run_tests from base dir /tmp/easy_install-4KKbzW/vsc-base-2.4.18/temp/easy_install-pdMQNo/vsc-install-0.9.19 (using executable /tmp/easy_install-4KKbzW/vsc-base-2.4.18/temp/easy_install-pdMQNo/vsc-install-0.9.19/setup.py)
INFO: no prospector support in py26 (or older)
WARN: cleanup lib/vsc_install.egg-info
INFO: removing 'lib/vsc_install.egg-info' (and everything under it)
INFO: generated list: ['vsc.install', 'vsc']
INFO: generated packages list: ['vsc.install', 'vsc']
INFO: makesetupcfg set to True, (re)creating setup.cfg
INFO: found license /tmp/easy_install-4KKbzW/vsc-base-2.4.18/temp/easy_install-pdMQNo/vsc-install-0.9.19/LICENSE with md5sum 5f30f0716dfdd0d91eb439ebec522ec2
INFO: Found license name LGPLv2+ and classifier License :: OSI Approved :: GNU Lesser General Public License v2 or later (LGPLv2+)
INFO: setting license LGPLv2+
INFO: No name defined, trying to determine it
INFO: found match url https://github.com/hpcugent/vsc-install in /tmp/easy_install-4KKbzW/vsc-base-2.4.18/temp/easy_install-pdMQNo/vsc-install-0.9.19/PKG-INFO
INFO: found match name vsc-install in /tmp/easy_install-4KKbzW/vsc-base-2.4.18/temp/easy_install-pdMQNo/vsc-install-0.9.19/PKG-INFO
INFO: Removing None download_url
INFO: get_name_url returns {'url': 'https://github.com/hpcugent/vsc-install', 'name': 'vsc-install'}
INFO: using long_description vsc-install provides shared setuptools functions and classes for python libraries developed by UGent's HPC group
INFO: generated list: []
INFO: generated scripts list: []
WARN: zip_safe flag not set; analyzing archive contents...
WARN: vsc.fancylogger: module references __file__
WARN: vsc.install.shared_setup: module references __file__
WARN: vsc.install.shared_setup: module references __path__
WARN: vsc.install.shared_setup: module MAY be using inspect.getsource
INFO: 
Installed /tmp/easy_install-4KKbzW/vsc-base-2.4.18/vsc_install-0.9.19-py2.6.egg
WARN: zip_safe flag not set; analyzing archive contents...
WARN: vsc.utils.exceptions: module MAY be using inspect.getouterframes
WARN: vsc.utils.fancylogger: module MAY be using inspect.stack
WARN: vsc.utils.generaloption: module MAY be using inspect.stack
WARN: cleanup lib/vsc_install.egg-info
WARN: zip_safe flag not set; analyzing archive contents...
WARN: vsc.fancylogger: module references __file__
WARN: vsc.install.shared_setup: module references __file__
WARN: vsc.install.shared_setup: module references __path__
WARN: vsc.install.shared_setup: module MAY be using inspect.getsource
[[INFO]] running post install command 'easy_install --upgrade --prefix=/tmp/tmpPXpLWE/eb_stage1 vsc-base'
INFO: Searching for vsc-base
INFO: Reading http://pypi.python.org/simple/vsc-base/
INFO: Best match: vsc-base 2.4.18
INFO: Processing vsc_base-2.4.18-py2.6.egg
INFO: vsc-base 2.4.18 is already the active version in easy-install.pth
INFO: Installing optcomplete.bash script to /tmp/tmpPXpLWE/eb_stage1/bin
INFO: Installing startlogdaemon script to /tmp/tmpPXpLWE/eb_stage1/bin
INFO: Installing logdaemon script to /tmp/tmpPXpLWE/eb_stage1/bin
INFO: 
Using /tmp/tmpPXpLWE/eb_stage1/lib/python2.6/site-packages/vsc_base-2.4.18-py2.6.egg
INFO: Processing dependencies for vsc-base
INFO: Finished processing dependencies for vsc-base
[[INFO]] 

+++ STAGE 2: installing EasyBuild in /home/steve-s/.local/easybuild with EasyBuild from stage 1...


== temporary log file in case of crash /tmp/eb-HW5GVv/easybuild-mN0UDT.log
== processing EasyBuild easyconfig /tmp/tmpPXpLWE/EasyBuild-2.6.0.eb
== building and installing Core/EasyBuild/2.6.0...
== fetching files...
== creating build dir, resetting environment...
== unpacking...
== patching...
== preparing...
== configuring...
== building...
== testing...
== installing...
== taking care of extensions...
== postprocessing...
== sanity checking...
== cleaning up...
== creating module...
== permissions...
== packaging...
== COMPLETED: Installation ended successfully
== Results of the build can be found in the log file /home/steve-s/.local/easybuild/software/Core/EasyBuild/2.6.0/easybuild/easybuild-EasyBuild-2.6.0-20160308.094638.log
== Build succeeded for 1 out of 1
== Temporary log file(s) /tmp/eb-HW5GVv/easybuild-mN0UDT.log* have been removed.
== Temporary directory /tmp/eb-HW5GVv has been removed.
[[INFO]] Done!
[[INFO]] 
[[INFO]] EasyBuild v2.6.0 was installed to /home/steve-s/.local/easybuild, so make sure your $MODULEPATH includes /home/steve-s/.local/easybuild/modules/all
[[INFO]] 
[[INFO]] Run 'module load EasyBuild', and run 'eb --help' to get help on using EasyBuild.
[[INFO]] Set $EASYBUILD_MODULES_TOOL to 'Lmod' to use the same modules tool as was used now.
[[INFO]] 
[[INFO]] By default, EasyBuild will install software to $HOME/.local/easybuild.
[[INFO]] To install software with EasyBuild to /home/steve-s/.local/easybuild, make sure $EASYBUILD_INSTALLPATH is set accordingly.
[[INFO]] See http://easybuild.readthedocs.org/en/latest/Configuration.html for details on configuring EasyBuild.

steve-s@wrk012 > module use $EASYBUILD_PREFIX/modules/all

steve-s@wrk012 > module load Core/EasyBuild         
     
steve-s@wrk012 > python -m test.framework.suite

Traceback (most recent call last):
  File "/usr/lib64/python2.6/runpy.py", line 122, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.6/runpy.py", line 34, in _run_code
    exec code in run_globals
  File "/home/steve-s/.local/easybuild/software/Core/EasyBuild/2.6.0/lib/python2.6/site-packages/easybuild_framework-2.6.0-py2.6.egg/test/framework/suite.py", line 56, in <module>
    import test.framework.asyncprocess as a
  File "/home/steve-s/.local/easybuild/software/Core/EasyBuild/2.6.0/lib/python2.6/site-packages/easybuild_framework-2.6.0-py2.6.egg/test/framework/asyncprocess.py", line 33, in <module>
    from test.framework.utilities import EnhancedTestCase
  File "/home/steve-s/.local/easybuild/software/Core/EasyBuild/2.6.0/lib/python2.6/site-packages/easybuild_framework-2.6.0-py2.6.egg/test/framework/utilities.py", line 39, in <module>
    from vsc.utils.testing import EnhancedTestCase as _EnhancedTestCase
  File "/home/steve-s/.local/easybuild/software/Core/EasyBuild/2.6.0/lib/python2.6/site-packages/vsc_base-2.4.18-py2.6.egg/vsc/utils/testing.py", line 33, in <module>
    from vsc.install.testing import TestCase as EnhancedTestCase
ImportError: No module named install.testing

steve-s@wrk012 > ls /home/steve-s/.local/easybuild/software/Core/EasyBuild/2.6.0/lib/python2.6/site-packages
distribute-0.7.3-py2.6.egg             setuptools-20.2.2-py2.6.egg
easybuild_easyblocks-2.6.0-py2.6.egg   setuptools.pth
easybuild_easyconfigs-2.6.0-py2.6.egg  site.py
easybuild_framework-2.6.0-py2.6.egg    site.pyc
easy-install.pth                       vsc_base-2.4.18-py2.6.egg
/jobs/vot

steve-s@wrk012 > cat /home/steve-s/.local/easybuild/software/Core/EasyBuild/2.6.0/lib/python2.6/site-packages/*.pth
import sys; sys.__plen = len(sys.path)
./distribute-0.7.3-py2.6.egg
./setuptools-20.2.2-py2.6.egg
./vsc_base-2.4.18-py2.6.egg
/tmp/tmpPXpLWE/EasyBuild/2.6.0/dummy-dummy/vsc-base-2.4.18/.eggs/vsc_install-0.9.19-py2.6.egg
./easybuild_framework-2.6.0-py2.6.egg
./easybuild_easyblocks-2.6.0-py2.6.egg
./easybuild_easyconfigs-2.6.0-py2.6.egg
import sys; new = sys.path[sys.__plen:]; del sys.path[sys.__plen:]; p = getattr(sys, '__egginsert', 0); sys.path[p:p] = new; sys.__egginsert = p + len(new)
./setuptools-20.2.2-py2.6.egg


steve-s@wrk012 > python -c "import setuptools; print setuptools.__version__; print setuptools.__file__"
20.2.2
/home/steve-s/.local/easybuild/software/Core/EasyBuild/2.6.0/lib/python2.6/site-packages/setuptools-20.2.2-py2.6.egg/setuptools/__init__.pyc

`

**Comment by boegel** [comment] 2016-03-08 10:32
The `/tmp/tmpPXpLWE/EasyBuild/2.6.0/dummy-dummy/vsc-base-2.4.18/.eggs/vsc_install-0.9.19-py2.6.egg` entry you have in `easy-install.pth` is the problem...

I'll try and see if I can reproduce this.

@ukgeorge Which OS is this?

**Comment by ukgeorge** [comment] 2016-03-08 10:41
Thanks

steve-s@wrk012 > cat /etc/centos-release
CentOS release 6.7 (Final)

**Comment by boegel** [comment] 2016-03-09 15:45
@ukgeorge the bootstrap script just got updated (see #1660)

Can you try redownloading it to see if you still have the problem you reported?

I must say I'm not 100% sure yet what's going on, but let's first see if the current version of the bootstrap script still suffers from this problem.

If you're still seeing the same problem, please perform the bootstrap with `$EASYBUILD_BOOTSTRAP_DEBUG` defined, as follows:

```bash
EASYBUILD_BOOTSTRAP_DEBUG=1 python bootstrap_eb.py <prefix> 2>&1 | tee eb.log
```

and then share the contents of `eb.log` (e.g. via https://gist.github.com/)

**Comment by ukgeorge** [comment] 2016-03-09 18:19
I still get the same error. ImportError: No module named install.testing

Here's a link to the results of the log

https://gist.github.com/ukgeorge/ee2800a330adc1bcd0eb

**Comment by ukgeorge** [comment] 2016-03-09 18:33
Sorry, that link should be

https://gist.github.com/ukgeorge/733a07a478735de219e6

**Comment by boegel** [comment] 2016-03-09 19:39
@ukgeorge: that last gist shows a successful bootstrap running to completion?

**Comment by ukgeorge** [comment] 2016-03-10 09:42
The boostrap runs fine.

But python -m test.framework.suite fails with

 File "/usr/lib64/python2.6/runpy.py", line 122, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.6/runpy.py", line 34, in _run_code
    exec code in run_globals
  File
"/home/steve-s/.local/easybuild/software/EasyBuild/2.6.0/lib/python2.6/site-packages/easybuild_framework-2.6.0-py2.6.egg/test/framework/suite.py",
line 56, in <module>
    import test.framework.asyncprocess as a
  File
"/home/steve-s/.local/easybuild/software/EasyBuild/2.6.0/lib/python2.6/site-packages/easybuild_framework-2.6.0-py2.6.egg/test/framework/asyncprocess.py",
line 33, in <module>
    from test.framework.utilities import EnhancedTestCase
  File
"/home/steve-s/.local/easybuild/software/EasyBuild/2.6.0/lib/python2.6/site-packages/easybuild_framework-2.6.0-py2.6.egg/test/framework/utilities.py",
line 39, in <module>
    from vsc.utils.testing import EnhancedTestCase as _EnhancedTestCase
  File
"/home/steve-s/.local/easybuild/software/EasyBuild/2.6.0/lib/python2.6/site-packages/vsc_base-2.4.18-py2.6.egg/vsc/utils/testing.py",
line 33, in <module>
    from vsc.install.testing import TestCase as EnhancedTestCase
ImportError: No module named install.testing


Is there a Debug flag I can pass to the test framework suite

**Comment by boegel** [comment] 2016-03-15 08:47
@ukgeorge Sorry, I was mixing things up, thank you for clarifying that.

There's nothing much to debug for the tests, the issue is with the bootstrap script itself.
Basically what's going on is that the installation of the `vsc-install` package (which is a dependency for `vsc-base`, which is in turn a dependency for EasyBuild) from stage1 is reused for stage2.

But, since the stage1 installation is done in a temporary location which is cleaned up at the end of the bootstrap procedure, it is no longer around after the bootstrap.

`vsc-install` is required to run the tests, and only for the tests (your EasyBuild installation itself is probably perfectly fine).

I'll look into why we haven't noticed this before, and also into fixing this ASAP by enhancing the bootstrap script.

**Comment by boegel** [comment] 2016-03-15 08:57
@ukgeorge what does this print *before* you load the EasyBuild module?

```
python -c "import setuptools; print setuptools.__version__; print setuptools.__file__"
easy_install --version
```

**Comment by boegel** [comment] 2016-03-15 10:50
OK, I reproduced the problem on a CentOS 6 system, I'll see how I can fix this...

**Comment by boegel** [comment] 2016-03-15 12:43
This problem seems to only occur when you don't have a `setuptools` available on the system...

It should be fixed with the change in the bootstrap script being proposed in https://github.com/hpcugent/easybuild-framework/pull/1668 (it fixed it on the system I was testing).

@ukgeorge Are you up for testing that change, and see if it fixes the problem you're having?

**Comment by ukgeorge** [comment] 2016-03-15 23:13
Sorry, for the delay in getting back. I've been out the office.

I'll look at testing this tomorrow when I get in.

**Comment by boegel** [comment] 2016-03-16 07:50
@ukgeorge since the problem is fixed as far as I can tell, the pull request is already merged, so you can just re-download the bootstrap script as mentioned in the documentation (http://easybuild.readthedocs.org/en/latest/Installation.html#bootstrapping-procedure)

**Comment by ukgeorge** [comment] 2016-03-16 08:22
I have a separate issue now as our internet connection goes through a proxy.

Traceback (most recent call last):
  File "bootstrap_eb.py", line 760, in <module>
    main()
  File "bootstrap_eb.py", line 557, in main
    distribute_egg_dir = stage0(tmpdir)
  File "bootstrap_eb.py", line 243, in stage0
    distribute_setup_main(version="0.6.49-patched1")
  File "/tmp/tmptKwnFI/distribute_setup.py", line 558, in main
    tarball = download_setuptools(version=version,
download_base=options.download_base)
  File "/tmp/tmptKwnFI/distribute_setup.py", line 213, in
download_setuptools
    src = urlopen(url)
  File "/usr/lib64/python2.6/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib64/python2.6/urllib2.py", line 397, in open
    response = meth(req, response)
  File "/usr/lib64/python2.6/urllib2.py", line 510, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.6/urllib2.py", line 435, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.6/urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.6/urllib2.py", line 518, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 407: Proxy Authentication Required


I have 'http_proxy' defined as an environment variable which is picked up
fine by wget and curl but I think urllib2 may not observe the proxy
environment variable in python 2.6. It's mentioned in the 2.7 documentation
but not 2.6. I guess I could build python 2.7 outside of easybuild and use
that as a starting point. I don't think python 2.7 is available as an rpm
for Centos 6.7.

I guess this issue only occurs with Python 2.6 where proxy authentication
is required. I'll see if I can find a workaround but any advise greatly
appreciated.

**Comment by boegel** [comment] 2016-03-16 08:36
@ukgeorge `urllib2` should pick up on `http_proxy`, both in Python 2.6.x and Python 2.7.x.

Are you sure you're defining it correctly w.r.t. the authentication required, i.e. `http://username:password@proxy_url:port`? Cfr. http://stackoverflow.com/questions/34079/how-to-specify-an-authenticated-proxy-for-a-python-http-connection

**Comment by ukgeorge** [comment] 2016-03-16 08:48
Yes, that's exactly as I have it.

    export http_proxy="http://username:password@proxy_url:port"

Both curl and wget pick up the http_proxy environment variable and work
fine.

From here: https://docs.python.org/2/library/urllib2.html
python 2.7 mentions detecting proxy environment variables.

    In addition, if proxy settings are detected (for example, when a *_proxy
environment variable like http_proxy is set), ProxyHandler
<https://docs.python.org/2/library/urllib2.html#urllib2.ProxyHandler> is
default installed and makes sure the    requests are handled through the
proxy.

but https://docs.python.org/2.6/library/urllib2.html has no mention of
*_proxy environment detection

**Comment by boegel** [comment] 2016-03-16 09:55
@ukgeorge it does mention `http_proxy` at https://docs.python.org/2.6/library/urllib2.html ...

Can you try defining `https_proxy` too? Not sure if that makes sense, but it's worth a try.

I'm not sure if there's much we can do to fix this on our side, other than making sure the bootstrap can be done 'offline'.
There's already some support for that (see http://easybuild.readthedocs.org/en/latest/Installation.html#bootstrapping-using-supplied-source-tarballs), but not fully (stage0 still downloads from PyPI, and so will stage1/2 for `vsc-install`).

**Comment by ukgeorge** [comment] 2016-03-16 10:27
Thanks, Yes, I also have https_proxy set.

 I'll build up python 2.7 from source and hopefully that will fix the issue.

**Comment by ukgeorge** [comment] 2016-03-16 18:07
It would seem urllib2 requires http_proxy and https_proxy environment variables to be capitalised so

HTTP_PROXY ...
HTTPS_PROXY ..

works fine

**Comment by boegel** [comment] 2016-03-16 18:37
That's one thing that came to mind, but I figured it wasn't going to help since `HTTP_PROXY` isn't mentioned anywhere in the Python documentation.

So, the problems with bootstrapping EasyBuild are resolved?

If so, please close this issue.

**Closed** 2016-03-17 11:03 UTC
